### ISSUE TITLE
Que signifie le préfix "lo" sur les modules angularjs ?

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#108]
Les modules AngularJS s'appellent « loRebuildIndex », « loPatient »… etc. Que signifie ce « lo » ?

**Comment by opi** [comment]
LibreOsteo ?

**Comment by JocelynDelalande** [comment]
@opi ça se tient :-)

**Comment by jbgury** [comment]
Bien vu :) , le préfixe LibreOsteo pour les modules qui sont dans l'espace de nommage du produit :)
