### ISSUE TITLE
Comment gérer la traduction depuis Angular ?

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#109]
Je ne vois pas de code existant permettant de traduire des chaînes depuis angular (pour le faire au niveau de la template django, il y a plein d'exemples et ça fonctionne comme il faut).

Je voudrais faire qqch du genre `{$ trans foo.var $}` ou `{$ gettext(foo.var) $}`, mais ne vois pas où c'est utilisé

- Je vois que angular-i18n est inclut en dépendance (mais est-il utilisé ?)
- Je vois une requête `/jsi18n/` passer, mais idem, je ne suis pas certain de voir si il est mis en œuvre.

Bref, me mettre sur la piste serait bienvenu :-)

**Comment by JocelynDelalande** [comment]
J'ai l'impression, en l'état, qu'angular-i18n est listé comme dépendance bower mais pas utilisé, et qu'on pourrait le retirer des dépendances.

J'aimerais autant, que l'on utilise le mécanisme gettext de Django pour le JS partout, afin d'éviter d'avoir plusieurs mécanismes d'interationalisation qui cohabitent. Qu'en pensez-vous ?

Le point où on ne sait pas faire d'i18n actuellement est les templates angularjs ; mais je suis à peu près certain que l'on pourrait bricoler l'injection de la fonction `gettext` de django sous forme de pipe angularjs, pour faire des choses genre :

    {{ 'machaîne' | gettext }}

**Comment by jbgury** [comment]
angular-i18n est utilisé vraiment pour le formattage de date/heure ça n'a assez peu d'intéret je te l'accorde. L'idée était de garder une seule source des traductions depuis la gestion django comme tu l'auras compris.
la fonction gettext étant déjà disponible en effet, un filtre angularjs pour faire ça devrait se faire très simplement

**Comment by jbgury** [comment]
un filtre fourni par le module loUtils permet de traduire depuis un objet dans un contexte angular.
(voir implémentation #77 )
` {$ value | translate $}`
