### ISSUE TITLE
Retirer les commentaires de contexte des fichiers `.po`

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#111]
Les fichiers `.po` ressemblent à ça : 

```po

#: templates/partials/office-settings.html:8
msgid "General"
msgstr "Général"

#: templates/partials/office-settings.html:13
msgid "Office"
msgstr "Cabinet"

#: templates/partials/office-settings.html:125
#: templates/partials/user-profile.html:63
msgid "Update"
msgstr "Mettre à jour"

#: templates/partials/office-settings.html:132
msgid "Settings was updated"
msgstr "Les paramètres ont été mis à jour"

#: templates/partials/office-settings.html:134
msgid "Users"
msgstr "Utilisateurs"

#: templates/partials/office-settings.html:139
msgid "Add user"
msgstr "Ajouter un utilisateur"
```

Ils sont générés par la commande `./manage.py makemessages`.

Ce qui est pénible c'est que les lignes de commentaires (avec un '#') changent à chaque fois qu'une ligen de code est insérée… Quand ces fichiers sont versionnés via git, cela produit des diffs et des commits très « bruyants »… Et beaucoup de travail de résolution de conflits lors de merges…

À mon sens, les inconvénients de ces commentaires en dépassent les avantages.

OK pour utiliser `./manage.py makemessages --no-location` qui génère les `.po` sans ces lignes embarassantes ? 

Je suis volontaire pour écrire une mini-doc sur comment fonctionne la localisation dans LO.

**Comment by jbgury** [comment]
parfait pour moi
