### ISSUE TITLE
La page de login a perdu une conf css

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#120]
@opi j'avoue ne pas maîtriser css aussi bien que toi...
Pourrais tu m'expliquer pourquoi en introduisant form-wrapper:empty, la class form-signin ne s'applique plus sur la page /account/login.html ?

Merci bien

**Comment by jbgury** [comment]
le changement d'ordre des styles semblent corriger le problème mais je suis curieux de comprendre pourquoi

**Comment by opi** [comment]
Le format des commentaires CSS n'était pas bon, j'avais par reflexe utilisé une syntax qui ne fonctionne qu'avec un preprocesseur LESS/Sass (`//`), alors que CSS n'utilise que les commentaires avec `/* */`

Du coup, les regles CSS qui étaient après mon erreur de syntaxe n'étaient pas pris en compte ; Le soucis avait donc disparu quand tu avais bougé l'erreur de syntaxe en fin de fichier.

c'est corrigé dans la PR https://github.com/libreosteo/Libreosteo/pull/127

**Comment by jbgury** [comment]
Ah ben oui je n'avais pas percuté en relisant;....
