### ISSUE TITLE
problème entre la version de cherrypy et six

### ISSUE THREAD

**Issue by littlejo** [libreosteo/LibreOsteo#125]
J'ai eu cette erreur lorsque j'ai voulu lancer libreosteo

  File "server.py", line 22, in <module>
    import cherrypy
  File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 73, in <module>
    from ._cptools import default_toolbox as tools, Tool
  File "/usr/lib/python2.7/site-packages/cherrypy/_cptools.py", line 33, in <module>
    from cherrypy.lib import auth_basic, auth_digest
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/auth_digest.py", line 8, in <module>
    from six.moves.urllib.request import parse_http_list, parse_keqv_list
ImportError: cannot import name parse_http_list

Il y a un problème similaire: https://github.com/cherrypy/cherrypy/issues/1685

Le changement vient du commit suivant qui requiert un six plus récent que 1.10 :
https://github.com/cherrypy/cherrypy/commit/67d60277785644d848e0d1193d8663148739f940

Deux choix possibles ::
* Mettre cherrypy à la version 10.2.2 (tester : ça foncctionne)
* Mettre à jour six à 1.11.0 ou plus récent et fixer la version de cherrypy (non tester)

**Comment by jbgury** [comment]
Merci pour cette analyse :+1:
