### ISSUE TITLE
Boucle en permanence sur `updateComponentPolyfill`

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#133]
Quand on ouvre la vue patient, et qu'on clique sur « Éditer », la fonction `updateComponentPolyfill()` semble appelée en boucle, en l'absence d'interaction utilisateur (on peut s'en rendre compte en ajoutant un console.log, ou bien simplement en notant le message qui se répète en boucle dans la console js : `inputwidgets already implemented for element # 14 polyfiller.js:1:7389`).

La fonction appelée en boucle : 

https://github.com/libreosteo/Libreosteo/blob/8c2018d088ca65751f8613e7424738fa2d793897/libreosteoweb/static/js/app/patient.js#L132-L139

Je n'ai pas vraiment le niveau/contexte et la connaissance de webshim nécessaire pour résoudre ce souci. J'ai par contre fait une bissection, et il semble que ce problème ait été introduit par 4e8a813de8f96af927501f68a22c4cf2ed461ecc

**Comment by jbgury** [comment]
oui en effet merci, je m'en occupe

**Comment by jbgury** [comment]
Voir la PR correspondante. Le watch s'assure que les composants de type date sont bien traités par webshim. L'intégration est minimale mais implique de s'appuyer sur l'état du composant. D'où cette PR.Merci à toi
