### ISSUE TITLE
Sortie de la 0.6 ou 0.5.8 ?

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#140]
On va avoir un paquet de nouvelles fonctionalités / modifications / corrections de bugs depuis la 0.5.7

Une fois #136 #137 #138 #139 #129 #114 intégrées, il serait peut-être judicieux de sortir une version ?

Les objectifs initiaux de la [0.6](https://github.com/libreosteo/Libreosteo/milestone/3) tels que fixés par @jbgury ne sont pas atteints, mais on a par ailleurs pas mal de changements notamment changements d'interface importants, donc ça pourrait mériter plus qu'une version patch, quite à déplacer certains tickets de la 0.6 telle que prévue actuellement vers une milestone 0.7 ?

Si je peux faire quoi que ça soit pour aider à cette sortie, je suis volontaire :-)

**Comment by littlejo** [comment]
Je trouve aussi que la prochaine version mérite d'être une version majeure (amélioration de l'interface + des fonctionnalités comme l'ajout de documents) bien que toutes les fonctionnalités prévues n'ont pas été développées. Rien empêche de les développer dans une version mineure (0.6.?).

J'imagine que la nouvelle version de libreosteo n'est pas encore sortie parce que @jbgury n'a pas le temps de se consacrer à cela.

**Comment by jbgury** [comment]
La prochaine version ne contiendra en effet pas tout ce qui est prévu. Mais il reste encore quelques points que je souhaiterais résoudre avant la sortie de la version : 
 - finalisation de deux devs de mon côté (filtre sur le thérapeute, et changement de date de consultation sur certains critères)
 - passage à python 3. Dans un premier temps support complet de python2 et python3, et rapidement supprimer le support python 3. 

Ensuite il me faut merger les dernières PR fournies mais j'aimerais les tester avant le merge. Pour le moment sur docker j'ai pas été très loin (je risque de merger sans vérifier...), et concernant la #114 j'ai un soucis à l'usage. Il faut que je vérifie avec les dernières modifications. Mais j'avoue le temps me manque cruellement.... Mais ça va se faire :)

**Comment by JocelynDelalande** [comment]
> Mais il reste encore quelques points que je souhaiterais résoudre avant la sortie de la version :
>
>     passage à python 3. […]

Est-ce bien urgent ?

Je vois deux raisons à ne pas se mettre la compatibilité Python 3 en objectif pour la prochaine version: 

- En tant que développeur, je suis partisan de passer à Python3, mais en tant qu'utilisateur, ça ne me change absolument rien (on bloque du fonctionnel par du non fonctionnel)
- En passant à Python3, nous allons probablementoublier quelques bugs liés à Python 3 (quasi inévitable, et ça peut être un peu partout dans le code). Aussi, il semblerait plus judicieux de ne pas ajouter le support Python3 juste avant une release, mais au contraire juste après une release, pour se laisser le temps de trouver ces probables bugs en développant par dessus.

Tout cela étant dit, je serais un développeur comblé lorsqu'on aura une compatibilité Python 3 :-)

> […], et concernant la #114 j'ai un soucis à l'usage. Il faut que je vérifie avec les dernières modifications. 

À ta dispo si besoin :-)

> Mais j'avoue le temps me manque cruellement.... Mais ça va se faire :)

Yes  ! Et merci d'avoir pris le temps de faire ce petit point.

**Comment by jbgury** [comment]
A travers les tests automatisés fonctionnels mis en place sur la branche develop et chaque PR, cela exécute les tests sur python2.7 et python3.6

Cela permet de couvrir la compatibilité sur les deux versions en vue d'un abandon de python2 dans une prochaine release.
Je propose donc que la 0.6 soit la version de la transition :

* Sortir la version 0.6.0 en 2.7
* Sortir une version 0.6.5 en python3 ( par exemple pour la numérotation de version)

La version 0.7 sera donc exclusivement python3

**Comment by jbgury** [comment]
I close this subject, because 0.6 is out with python 3 support.
