### ISSUE TITLE
Passage python2 vers python3

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#141]
Lors du passage de python 2 à python 3, les points suivants ont été identifiés à corriger : 
 - visualisation et génération d'une facture (compatibilité unicode 0,5 j)
 - industrialisation nettoyage base d'index whoosh recréation de la base d'index (2 j)

**Comment by littlejo** [comment]
J'ai essayé de déployer libreosteo avec python 3 (avec docker). Mais quand je clique Register the administrator, cela ne fonctionne pas :

> ERROR 2018-07-11 14:17:58,451 basehttp "GET /web-view/partials/register HTTP/1.1" 500 73491
> ERROR 2018-07-11 14:18:01,971 exception Internal Server Error: /web-view/partials/register
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
>     response = get_response(request)
>   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/Libreosteo/libreosteoweb/api/displays.py", line 157, in display_register
>     return render(request, 'partials/register.html', {'csrf_token' : request.COOKIES['csrftoken']})
> KeyError: 'csrftoken'
> ERROR 2018-07-11 14:18:02,098 basehttp "GET /web-view/partials/register HTTP/1.1" 500 73491

**Comment by jbgury** [comment]
Salut,
Je n'arrive pas à reproduire l'erreur en local.
Peux tu dumper le pip environnement obtenu avec l'installation dans docker ?
Voici le mien
```bash
$ pip freeze
backports.functools-lru-cache==1.5
cheroot==6.3.3
CherryPy==14.0.0
Django==1.11
django-appconf==1.0.1
django-compressor==2.2
django-filter==1.0.4
django-haystack==2.8.1
django-statici18n==1.4.0
djangorestframework==3.6.4
djangorestframework-csv==1.4.1
jaraco.functools==1.20
more-itertools==4.2.0
pkg-resources==0.0.0
portend==2.3
pytz==2018.5
rcssmin==1.0.6
rjsmin==1.0.12
setuptools-bower==0.2.0
six==1.11.0
sqlparse==0.2.4
tempora==1.13
Whoosh==2.7.0
```

**Comment by littlejo** [comment]
J'ai retesté là ça ne me fait plus de problème... Tant mieux :)

**Comment by littlejo** [comment]
Si jamais ça intéresse quelqu'un, je l'ai mis sur docker hub: littlejo/libreosteo-git-python3
Les sources sont sur ma branche git: docker_python3_new

**Comment by littlejo** [comment]
Il y a un soucis avec la nouvelle version de développement en python3 avec configparser :
```
python server.py 
Traceback (most recent call last):
  File "server.py", line 28, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

http://python-future.org/compatible_idioms.html

```
# Python 2 only:
from ConfigParser import ConfigParser

# Python 2 and 3 (after ``pip install configparser``):
from configparser import ConfigParser

```

**Comment by jbgury** [comment]
:+1:

**Comment by jbgury** [comment]
Depuis la branche robotfwk-test encore en cours , l'exécution de tests automatisés fonctionnels est mis en place. Cela exécute avec un environnement python2 et python3.
Cela permettra de s'assurer qu'un développement ne casse plus rien et est compatible sur les deux versions en attendant le passage définitif sur python3

**Comment by jbgury** [comment]
Tests ajoutés sur la branche develop exécution en python2 et python3.6.

**Comment by jbgury** [comment]
Je clos ce ticket
