### ISSUE TITLE
Ne plus avoir comme dépendance Bower

### ISSUE THREAD

**Issue by littlejo** [libreosteo/LibreOsteo#142]
J'ai ce warning quand je lance : npm install -g bower

`npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/`

**Comment by jbgury** [comment]
Oui j'ai eu la même et j'ai commencé à travailler sur la migration :)

**Comment by jbgury** [comment]
La branche winbuild-fix traite ce problème. Je dois encore exécuter quelques tests de build sous windows, et macOsX avant de pouvoir la merger mais cela devrait erradiquer cette vieille dépendance
