### ISSUE TITLE
netiface compilation

### ISSUE THREAD

**Issue by littlejo** [libreosteo/LibreOsteo#145]
Je n'arrive pas à pip install netiface : 
   building 'netifaces' extension
    gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -fPIC -DNETIFACES_VERSION=0.10.7 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_LL=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-x86_64-2.7/netifaces.o
    netifaces.c:131:28: fatal error: linux/tipc.h: No such file or directory
     #    include <linux/tipc.h>
                                ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-M2eL5j/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UdfxSc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-M2eL5j/netifaces/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'libreosteo' failed to build: The command '/bin/sh -c pip install -r Libreosteo/requirements/requ-py2.txt' returned a non-zero code: 1

**Comment by littlejo** [comment]
https://bitbucket.org/al45tair/netifaces/issues/47/cannot-install-under-alpine-linux
Il faut installer linux-headers :

> apk add linux-headers

**Comment by JocelynDelalande** [comment]
@littlejo thanks for sharing ! 

So, that issue would require a docker update and doc update as well, no ? Could deserve re-opening the issue, what do you think ?

**Comment by littlejo** [comment]
I think for desktop or server distribution, this requirement is installed by default. It's just for docker if you reach minimal image.

**Comment by JocelynDelalande** [comment]
> I think for desktop or server distribution, this requirement is installed by default. It's just for docker if you reach minimal image.

I doubt that linux-headers is installed by default on a Debian distribution, as there is only one very minimal system and optional packages sets. So IMHO, this dependency is definitely worth documenting !

**Comment by jbgury** [comment]
Hello guys,

I'm sorry about this dependency :/ I didn't see that on my both workstation. I suppose that the linux-headers package is installed by some drivers (like VirtualBox or Graphic Card) and I did not see this requirements.
I update the readme with that. Thank you both

**Comment by jbgury** [comment]
Docker build is updated, and README too, I think that we can consider this bug as closed, isn't it ?
