### ISSUE TITLE
pouvoir supprimer une fiche patient facturée et les consultations associées

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#150]
En tant qu'administrateur je dois pouvoir supprimer une fiche patient même si celle-ci est facturée, sans pour autant supprimer la facture générée.

Lorsque l'on "fiche" des personnes, c'est une obligation légale de devoir les "déficher".
cf : [question "Combien de temps pouvez-vous conserver les données que vous collectez sur vos patients?"](https://www.cnil.fr/fr/rgpd-et-professionnels-de-sante-liberaux-ce-que-vous-devez-savoir)
ou anciennement : [NS-050](https://www.cnil.fr/fr/declaration/ns-050-cabinet-medical-et-paramedical)

#43 : augmente les possibilés de ce ticket

**Comment by jbgury** [comment]
Si je comprends le besoin, ce serait en "un simple clic" vider la fiche de son contenu dans le but du respect légal. Aujourd'hui la suppression des données peut ếtre faite, il s'agit surtout de simplifier le "vidage" du dossier patient. C'est bien cela l'attendu ?

**Comment by jkiwi** [comment]
Oui c'est cela, l'idée est effectivement de pouvoir supprimer la fiche patient et toutes les consultations associées avec "un simple clic".
De ce que j'ai compris du fonctionnement actuel du logiciel, une fiche patient peut être supprimée si les consultations ont préalablement été supprimées. Or on ne peut pas supprimer les consultations clôturées/facturées. Ce ticket est donc lié avec #151 je pense.

**Comment by jbgury** [comment]
PR disponible, un message de confirmation est affichée avant la suppression (il faut cocher une case pour certifier avoir bien compris l'impact :) )
