### ISSUE TITLE
pouvoir supprimer les consultations individuellement

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#151]
En tant qu'administrateur il est intéressant de pouvoir supprimer une consultation individuellement même si elle est clôturée et facturée. En cas de doublon par exemple.

Cela ne doit pas supprimer la fiche patient, les autres consultations ou la facture associée.

**Comment by jbgury** [comment]
Une consultation facturée ne peut pas être supprimée, sinon la facturation de l'acte n'a plus de sens. Ou alors à quoi se raccroche une facture dans ce cas ? on saura tout de même que le patient a eu une consultation à tel jour. Comment un cas de doublon peut il arriver ? Serait il possible d'expliciter ce cas d'usage ?
merci

**Comment by jkiwi** [comment]
La facture peut toujours être listée dans la nouvelle entrée de menu "comptabilité" par exemple ? Et être vue même si la fiche de consulation est supprimée ?
Il y a une différence entre les infos présentes dans une facture et toutes les infos médicales présentes dans une fiche de consultation.
J'avoue ne pas savoir si il y a un délai légal de conservation des factures...

Il est vrai qu'un cas de doublon est assez difficile avec libreosteo (ce qui est une très bonne chose :-) ) mais pas impossible...

Je n'ai pas essayé de clôturer plusieurs fiches de consultations d'un même patient un même jour pour voir si cela était possible (certe il faudrait vraiment le vouloir, mais bon... suite à un problème technique ?)

Par ailleurs on peut récréer un patient déjà existant en se trompant juste d'une lettre (suite à une incompréhension) et refaire des consultations avec ce "nouveau profile". Le jour ou l'on s'en rend compte, on peut "fusionner" les fiches consultations (avec un copier/coller par exemple), mais pas supprimer les doublons si cloturés.
C'est encore plus vrai sur un cabinet ou travail plusieurs ostéopathes.
(Et j'ai déjà eu l'exemple avec d'autres logiciels lors d'un remplacement et avec des noms comme Dupond/Dupont ; Ménard/Mainard ; ...,).

Également, j'ai vu qu'on ne pouvait pas créer un patient avec les mêmes noms et date de naissance, ce qui évite les doublons justement.
C'est très rare, mais j'ai déjà eu le cas d'homonyme né le même jour. (mais c'est un autre sujet...).

**Comment by jbgury** [comment]
> La facture peut toujours être listée dans la nouvelle entrée de menu "comptabilité" par exemple ? Et être vue même si la fiche de consulation est supprimée ?
oui ce serait possible
> J'avoue ne pas savoir si il y a un délai légal de conservation des factures...

Difficile de savoir le délai pour les professions libérales. Pour les entreprises, c'est 10 ans après la date de cloture de l'exercice dans laquelle s'inscrit la facture éditée.

>Je n'ai pas essayé de clôturer plusieurs fiches de consultations d'un même patient un même jour pour voir si cela était possible (certe il faudrait vraiment le vouloir, mais bon... suite à un problème technique ?)

Oui c'est possible, mais cela génèrera aussi deux factures (si facturation il y a) ensuite une consultation en doublon est elle un problème ? (même jour sur même motif?)

> Par ailleurs on peut récréer un patient déjà existant en se trompant juste d'une lettre (suite à une incompréhension) et refaire des consultations avec ce "nouveau profile". Le jour ou l'on s'en rend compte, on peut "fusionner" les fiches consultations (avec un copier/coller par exemple), mais pas supprimer les doublons si cloturés.
> C'est encore plus vrai sur un cabinet ou travail plusieurs ostéopathes.

C'est vrai, d'où la fonction de recherche à utiliser "tout le temps" pour se protéger à minima de ce genre de cas. Mais c'est pas exclus.
Une fusion de dossiers patients serait intéressante il me semble oui.

> Également, j'ai vu qu'on ne pouvait pas créer un patient avec les mêmes noms et date de naissance, ce qui évite les doublons justement.
> C'est très rare, mais j'ai déjà eu le cas d'homonyme né le même jour. (mais c'est un autre sujet...).

J'invite à utiliser les noms complémentaires du patient dans ce cas. Sinon risque de mélanger les deux dossiers patients... et là c'est plus de la fusion qu'il faut faire mais de déplacer des consultations d'un patient à un autre. C'est peut être ça l'orientation à prendre oui.

**Comment by JocelynDelalande** [comment]
Suite à discussion avec @jkiwi , le besoin initial (gestion des doublons) serait mieux couvert par une gestion de la fusion des patients. cf #214 

Ce besoin de suppression deviendrait alors très secondaire voire inutile ; @jkiwi je te laisse clore le ticket et @jbgury tu peux le ré-ouvrir si ça te semble pertinent :).
