### ISSUE TITLE
Enlever ou modifier le champ "nom de naissance" lors de la création d'une fiche

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#154]
Le champ "nom de jeune fille" n'est pas utile à la prise en charge des patientes.

Si besoin il est possible de mettre plusieurs noms dans le champs "nom de famille", que ce soit pour un homme ou pour une femme.

De plus une fois la fiche créé il n'est pas possible de le rajouter si laissé vide.

Des champs "nom" et "prénom" sont suffisant.

**Comment by jbgury** [comment]
Ce n'est pas la demande de tout le monde... Cette demande devrait être soumise à vote à mon sens... Ce sont des thérapeutes qui ont effectué cette demande.
(L'ajout a postériori est possible si vide à l'initialisation mais à la demande de certains thérapeutes n'est possible que si Sexe féminin est renseigné...)
Actuellement sur la branche develop

**Comment by jbgury** [comment]
Le nom de naissance est conservé pour le moment, et peut être mis à jour ou non à l'édition d'une fiche patient.

**Comment by jkiwi** [comment]
> Ce n'est pas la demande de tout le monde... Cette demande devrait être soumise à vote à mon sens... Ce sont des thérapeutes qui ont effectué cette demande.
> (L'ajout a postériori est possible si vide à l'initialisation mais à la demande de certains thérapeutes n'est possible que si Sexe féminin est renseigné...)
> Actuellement sur la branche develop

J'ai proposé cette modification après consultation d'une petite 10aine de collègues (aucun n'utilisant ce champ). Je l'ai également proposé car au début lors de la prise en main du logiciel, il m'est arrivé plusieurs fois de remplir le prénom danc cette case et ensuite de devoir corriger. Probablement que l'apellation « nom de jeune fille » me dérangeais également, mais cela a bien évolué avec #162 

Et je reviens sur mes propos : le fait de de mettre plusieurs noms dans le champ « nom de famille » n'est pas une bonne idée car cela apparaîtra sur la facture (je n'avais plus ça en tête).
De plus je peux tout à fait imaginer que des collègues puissent se servir de ce champ lorsque les patient·e·s changent de nom (divorce, remariage, ...) afin d'en garder une trace et les retrouver facilement grâce à la recherche quelque soit le nom donné par les patient·e·s lors de la prise de rendez-vous.

Je propose donc ici 2 nouvelles idées d'évolution : 
- rendre ce champ désactivable pour celles et ceux ne l'utilisant pas (à discuter il y a des "pour" et des "contres" à cela).
- Déplacer ce champ en 3ème position (après le prénom), pour que le choix de l'utiliser reste possible mais que l'enchaînement entre "nom de famille" et "prénom" soit plus fluide (à discuter également car je peux comprendre la logique de garder « les noms » côte à côte...)

Comme ce n'est pas un sujet urgent, peut-être vaut-il mieux le statu quo pour l'instant en attendant d'avoir plus de retour d'expérience.

**Comment by jkiwi** [comment]
ps : je ne sais pas si c'est l'usage, mais j'ai modifié le titre en conséquence...

**Comment by JocelynDelalande** [comment]
Suite à discussion avec @jkiwi (off), ce qui était vraiment embêtant c'était « nom de jeune fille ». À l'usage, la présence de ce champ n'est pas gênante, et ne semble pas justifier de s'embêter avec un paramètre pour le rendre désactivable.

@jkiwi je te laisse fermer.

et @jbgury  si tu n'es pas d'accord et souhaites ré-ouvrir, feel free :)
