### ISSUE TITLE
Retour visuel pour indiquer la suppression d'une consultation

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#155]
Lors de la suppression d'une consultation, rien n'indique que cela a été pris en compte (comme lors de la suppression d'une fiche patient ou il y a une redirection vers le tableau de bord).

(Branche de développement)

**Comment by jbgury** [comment]
Le retour actuel est : 
Fermeture de la consultation en cours qui est éditée, et retour à la liste des consultations existantes. Soit le niveau -1 avant la création de la facture.
Est ce qu'un message de notification informant la consultation supprimée conviendrait ?

**Comment by JocelynDelalande** [comment]
> Le retour actuel est :
> Fermeture de la consultation en cours qui est éditée, et retour à la liste des consultations existantes. Soit le niveau -1 avant la création de la facture.

Je confirme après avoir retesté sur un develop à jour.

(on a testé hier avec @jkiwi mais on était pas sur le tout dernier commit de develop, et on avait pas ce retour à la liste des consultations, l'interface restait sur la page de consult supprimée).

Cela dit, une petite notification pourrait être intéressant, mais c'était surtout le fait de rester sur la page de la fiche supprimée qui nous semblait problématique.
