### ISSUE TITLE
Pouvoir supprimer un utilisateur

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#156]
En tant qu'administrateur je dois pouvoir supprimer des utilisateurs qui ne travail plus au sein du cabinet.

(Branche de développement)

**Comment by jbgury** [comment]
Cela risque de poser problème sur les consultations effectuées par ces collaborateurs... 
On peut en revanche "vider" les informations liés à ces utilisateurs, mais les logins seraient conservés pour des raisons de traçabilités des consultations exercées

**Comment by JocelynDelalande** [comment]
un mécanisme de désactivation des comptes (et éventuellement vidage des champs) peut-être plus pratique techniquement qu'une suppression des comptes effectivement.

**Comment by jkiwi** [comment]
> Cela risque de poser problème sur les consultations effectuées par ces collaborateurs...
> On peut en revanche "vider" les informations liés à ces utilisateurs, mais les logins seraient conservés pour des raisons de traçabilités des consultations exercées

Merci pour ces précisions. En fait j'avais testé le logiciel en créant un second utilisateur qui n'avait pas vocation à rester... et que j'étais incapable de supprimer, d'ou le ticket.
Je n'avais pas en tête les difficultés techniques.

Une autre réflexion m'amène à penser que ça peut être bien de garder un historique des collaborateurs·trices qui sont intervenu·e·s au sein du cabinet.

Vos solutions semblent pertinentes en effet.

**Comment by JocelynDelalande** [comment]
Suite à discussion (off) avec @jkiwi et à cette discussion, ce mécanisme de désactivation semble suffisant.

Le seul cas intéressant serait de pouvoir retirer un utilisateur sans aucune fiche rattachée.  Et du coup la priorité de cette fonction est faible.

@jkiwi  pourrais-tu renommer le ticket en ce sens ? Merci.
