### ISSUE TITLE
Un administrateur doit pouvoir changer le nom/prénom d'un utilisateur

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#157]
Un admin ne peut pas définir ou changer le nom/prénom d'un utilisateur.
Seul l'utilisateur une fois connecter à son compte peut le faire.

(Branche de développement)

**Comment by jbgury** [comment]
Fixed with https://github.com/libreosteo/Libreosteo/commit/f58b7a9623759b81682e53bbd48f81b65d8149fa
