### ISSUE TITLE
Message d'avertissement si email patient invalide

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#158]
Dans l'onglet « info générales »,  si l'adresse email est invalide (ex: "coucou"), rien n'est sauvegardé et aucun message n'est affiché à l'utilisateur.

(Branche de développement)

**Comment by jbgury** [comment]
Un retour de type "validation" en rouge affichée sur la saisie de l'email pourrait il convenir ?
![image](https://user-images.githubusercontent.com/236368/47678979-5a9acc00-dbc3-11e8-8064-efc5d11504fd.png)

Dès que la saisie est correcte le champ passe en couleur normale : 
![image](https://user-images.githubusercontent.com/236368/47679004-71412300-dbc3-11e8-9f67-2e730e7a26b5.png)

**Comment by jkiwi** [comment]
Oui c'est très bien. Du coup si l'email n'a pas le bon format il est en rouge, mais est-il sauvegardé tel quel ? ou est-il supprimé lors du changement d'onglet ?

**Comment by jbgury** [comment]
Si invalide, il n'est pas sauvegardé non.
