### ISSUE TITLE
Changer le comportement de la touche entrée avec le champ de formulaire "motif"

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#160]
si on se positionne dans le champ "motif" d'une fiche de consultation, et qu'on appuie sur entrée : 
      - comportement attendu : une nouvelle ligne est crée (comme sur tous les autres champs)
      - comportement constaté : cloture de la consultation (techniquement = soumission du formulaire)
      - solution proposée : ne pas soumettre le formulaire à l'appui sur entrée dans ce champ (solution bis : passer ce champ en multiligne)

**Comment by jbgury** [comment]
Ok pour ne pas soumettre. En revanche la demande initiale des thérapeutes étaient la suivante : 

Motif : une ligne pour décrire le motif de la consultation. Si plus d'élements alors l'utilisation du "Détail de motif est à utiliser". C'est le rôle de ce champ.

L'unique ligne sur motif permet de synthétiser la demande d'une consultation et de l'afficher dans la vue synthétique des consultations.
C'est la demande initiale, si elle est remise en cause je propose de soumettre à vote.

Par contre, je confirme que l'appuie sur "Entrée" pour la soumission de la consultation reste un bug :)

**Comment by jbgury** [comment]
Je crois avoir finalement compris la demande. Du coup passer ce champ en multiligne me semble l'orientation à envisager 😊

**Comment by JocelynDelalande** [comment]
> Je crois avoir finalement compris la demande. Du coup passer ce champ en multiligne me semble l'orientation à envisager blush

Ou alors juste désactiver la soumission du formulaire à l'appui sur entrée ? (le caractère multiligne de ce champ brouillerait un peu la fonction du champ détaillé et risque de poser souci dans l'affichage timeline).

**Comment by jkiwi** [comment]
Le plus simple reste de désactiver l'usage de la touche entrée dans le champ de formulaire "motif".
Je suis d'accord pour dire qu'il faut garder la timeline synthétique (qui est par ailleurs très bien) et donc garder ce champ "motif" sur une seule ligne.

**Comment by jbgury** [comment]
Avec une mise à jour globale sur le dossier patient, lorsque l'on fait "Entrée" sur un champ simple, le formulaire technique n'est plus envoyé pour soumission. Le comportement du champ motif est donc maintenu à une seule ligne, et l'appui sur entrée ne sort pas de l'édition de la consultation
Comportement modifié sur la branche "develop"

**Comment by jbgury** [comment]
Fixed on develop branch
