### ISSUE TITLE
Changer le comportement de la touche entrée dans l'onglet "infos générales"

### ISSUE THREAD

**Issue by jkiwi** [libreosteo/LibreOsteo#161]
Dans l'onglet "infos générales", si on se positionne dans un champ à une ligne (ex: profession), et qu'on appuie sur la touche entrée:
      - comportement constaté : ouvre la popup de création de médecin
      - comportement attendu : rien (ou bien valide le formulaire, mais porteur de confusion, cf : #160 )

**Comment by jbgury** [comment]
Fixed on develop
