### ISSUE TITLE
« ne pas parler de nom de jeune fille » mais de « nom de naissance »

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#162]
À choisir, j'ai envie qu'on fasse un logiciel qui soit plutôt en avance qu'en retard sur la société sur les questions de genre et de sexisme :-)

Je fais suite à https://github.com/libreosteo/Libreosteo/issues/154#issuecomment-432815631 :

> (L'ajout a postériori [d'un nomb de jeune fille] est possible si vide à l'initialisation mais à la demande de certains thérapeutes n'est possible que si Sexe féminin est renseigné...)

Donc deux propositions concrètes:

- enlever ce comportement (discriminant, et pas cohérent avec le fonctionnement actuel du mariage et des changements de noms)
- parler de nom de naissance et non de nom de jeune fille

Qu'en pensez-vous ?

**Comment by jbgury** [comment]
parfait pour moi :)

**Comment by jbgury** [comment]
Les tests fonctionnels ont été mis à jour.
Je clos pour le moment
