### ISSUE TITLE
Numérotation des factures

### ISSUE THREAD

**Issue by Dalcim972** [libreosteo/LibreOsteo#173]
En tant qu'administrateur, je devrais pouvoir modifier la numérotation des factures : 

- modification du numéro de départ (factures 1 ou 10001 ou 100001) selon comment on a commencer à numéroter notre fichier factures patient papier pour créer un concordance 

- modification individuelle de certains numéros (ex: factures déchirés qui crée un saut de numérotation)

**Comment by jbgury** [comment]
:+1:  sur la modification du numéro de départ. Cette modification sera possible à l'installation de Libreosteo.
Ensuite sur la modification après génération d'une première facture devra suivre cette règle : 
 * la séquence de départ devra être supérieure strictement à la dernière facture générée sur le système. Il sera donc impossible de mettre une séquence de départ inférieure à la dernière facture.

Concernant la modification individuelle de certains numéro c'est interdit et illégal. Donc non ceci ne sera pas implémentée. La légalité réside dans le fait qu'il ne doit y avoit jamais de trou dans la suite des factures. Une facture déchirée... n'existe pas. En effet, une facture éditée reste un document légal, s'il y a une erreur, alors il faut annuler la facture. Ne jamais la détruire.

C'est plutôt l'annulation qui est à traiter par ceci. Je créé donc un ticket là dessus. (voir #174 )

**Comment by jbgury** [comment]
Ready for the version 0.6.0
