### ISSUE TITLE
Annuler une facture

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#174]
En tant que thérapeute je dois pouvoir annuler une facture éditée.
L'annulation génère une facture qui compense exactement la somme éditée dans la facture précédente, en précisant l'annulation de la facture avec son numéro.

Le compte client est donc à l'équilibre, la séquence des factures est respectée et le document est légal.

Une consultation pourra donc avoir plusieurs factures. Une facture pouvant annuler une autre

**Comment by Dalcim972** [comment]
Pour rester sur le domaine des factures : 
- je dois pouvoir (si cela reste légal) avoir la possibilité de modifier si nécessaire le nom qui apparait sur la facture du patient (généralement cela arrive à la demande du patient) 
Est-ce possible ?

**Comment by jbgury** [comment]
Non ce n'est pas légal. En revanche, il suffirait d'annuler la facture générée, de changer le nom du patient et de générer une facture pour arriver au même résultat tout en gardant trace des éléments de facturation (qui est légal)

**Comment by jbgury** [comment]
Pris en compte par la PR #177 
Développement effectué sur la branche Develop
