### ISSUE TITLE
anciennes factures invisibles

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#184]
Depuis la refonte de la facturation, les anciennes factures (avant la modification de la facturation) sont invisibles sur les fiches consult.

testé avec @jkiwi

**Comment by jbgury** [comment]
Une sauvegarde de la base avant migration avait été opérée ?

**Comment by jbgury** [comment]
Solved on master and develop branch. Wait for confirmation about the database was a test database no a production database

**Comment by JocelynDelalande** [comment]
> Une sauvegarde de la base avant migration avait été opérée ?

Oui, du coup ça devrait être jouable pour rejouer la migration corrigée.

> Une sauvegarde de la base avant migration avait été opérée ?

Oui :).

Bien joué pour le fix. 

D'un point de vue plus général, une pratique que je trouve… intéressante est de ne jamais (sauf cas de force majeure) revenir sur une migration qui a été diffusée sur une branche principale (master/develop), et de systématiquement corriger via une autre migration.

Évidemment, l'impact n'est que sur les utilisateur·ice·s qui utilisent le git, mais ça permet quand même de gagner en sérénité (en sacrifiant une certaine « pureté », mais bon, ça…).

**Comment by jbgury** [comment]
Entièrement d'accord avec toi. C'est ce que j'ai fait pour #183. Mais là le fixe était plus compliqué et plus hasardeux. Il était plus sûr pour les données de corriger la migration.
Une boulette de ma part lors de l'écriture de la migration. J'ai cherché les causes de comment j'en suis arrivé à ce résultat et j'ai trouvé.. j'ai fais cette fonctionnalité par morceaux de 5 à 10min par jour faute de temps et j'ai raté une tâche 😞

**Comment by jbgury** [comment]
Je peux clore du coup, merci encore

**Comment by JocelynDelalande** [comment]
:+1: j'ai pu valider ce matin : le fix fonctionne !

**Comment by jbgury** [comment]
merci
