### ISSUE TITLE
New examination : button end of editing does not exist anymore

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#201]
When we start a new examination, the just created examination is in editing mode, and you can input any information about the examination.

But it is impossible to save the current examination by clicking on "End of editing".

The only way to save it is to close the examination...

**Comment by JocelynDelalande** [comment]
IIRC, that issue is solved by #139

**Comment by jbgury** [comment]
:+1:

**Comment by jbgury** [comment]
Solved with #205 merging
