### ISSUE TITLE
Windows : Upgrading from 0.5.7 to 0.6.0 does not work

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#202]
After upgrading the application from 0.5.7 to 0.6.0 on Windows, it does not work.

The workaround is to uninstall the application and install the 0.6.0 after.

This workaround could be done before or after the upgrading.

**Comment by JocelynDelalande** [comment]
@jbgury so IMHO, better not to advise the upgrade to end-users on windows.

Does the workaround without any further precaution would lead to data loss ?

**Comment by jbgury** [comment]
no, there is no precaution just uninstall and reinstall. Data are not lost but kept. The problem comes from a conflict with some libraries which are present with the version 0.5.7 (32bits python2.7) and the 0.6.0 (64 bits, python 3.6).
Uninstalling remove all previously installed libraries, and installing after the 0.6.0 solves the issue with only the expected files and libraries.

Only the installation process has to be rebuilt.

**Comment by jbgury** [comment]
Installer updated to perform uninstallation before installing. Tested on fresh Win 10 installation with a previous 0.5.7 version before.

**Comment by jbgury** [comment]
see the installer on https://github.com/libreosteo/Libreosteo/releases/tag/0.6.0

**Comment by JocelynDelalande** [comment]
> no, there is no precaution just uninstall and reinstall. Data are not lost but kept.

Thanks for the clarification :).

> see the installer on https://github.com/libreosteo/Libreosteo/releases/tag/0.6.0

I am not sure to understand : did you modified 6.0 release or will this change come in a 0.6.1 or something like that ?

**Comment by jbgury** [comment]
> I am not sure to understand : did you modified 6.0 release or will this change come in a 0.6.1 or something like that ?

No change on the 0.6.0, the installer for 0.6.0 was rebuilt to add a process for uninstalling before installing due to change of the underlying. No change on the code itself.

**Comment by JocelynDelalande** [comment]
OK, thanks :).
