### ISSUE TITLE
Factures - Pouvoir choisir si besoin de faire un avoir ou pas 

### ISSUE THREAD

**Issue by Dalcim972** [libreosteo/LibreOsteo#204]
Lors d'une annulation de facture un avoir est automatiquement crée (+1) décalant de +2 la prochaine facture que l'on fait. 

Dans mon cas particulier, cela me crée un décalage qui avait été réglé au départ par l'ajout de la fonction d'annulation de facture par rapport à mon fichier facture papier. Quand je fais une annulation de facture papier je ne fais pas d'avoir (par exemple si je me suis trompé sur le montant, nom, etc..) et je rempli la facture suivante sans déchirer la précédente que j'archive avec annulation marqué dessus.
Alors si c'est illégal, éclairez ma lanterne. Sinon, j'aimerais comprendre le système d'avoir crée sur votre fonctionnalité. 

Sinon serait-il possible d'avoir le choix par rapport au système d'avoir de la fonctionnalité de facture ? 
Sinon si c'est obligatoire pourquoi ne pas avoir une numérotation différente pour les avoirs  (exemple : F000001 facture et A00001 pour les avoirs) ???

Merci d'avance.

**Comment by jbgury** [comment]
Bonjour, en effet, le système aujourd'hui créé systématiquement un avoir en cas d'annulation, cela permet un équilibre dans la comptabilité. Dans la liste comptabilité et l'export Excel tout est à l'équilibre.
En revanche , je ne comprends pas cette phrase dans votre explication : 

> Dans mon cas particulier, cela me crée un décalage qui avait été réglé au départ par l'ajout de la fonction d'annulation de facture par rapport à mon fichier facture papier

Car la fonction d'annulation a de ce fait créé un avoir.
On peut envisager d'annuler une facture par une autre en effet, c'est tout à fait possible et légal. Disons que les deux méthodes sont possibles, et en effet ici c'est la première méthode d'avoir qui a été mise en oeuvre, encore une fois par respect de l'équilibre.
Mais la proposition de paramétrer la création d'avoir ou non est possible.

Par contre, j'ai une question supplémentaire, pourquoi tenir deux systèmes de facturation : dans le logiciel et par papier ? 
Pour le coup, je ne sais pas si c'est très légal, mais je ne suis pas compétent pour le dire.

**Comment by Dalcim972** [comment]
Bonjour et merci pour la prise en compte de mon soucis (qui n'en est surement pas un suivant le contexte)

J'ai oublié de préciser que dans mon cas particulier le décalage dont je parle se crée au niveau des numéros de factures (exemple : la facture 00081 est erroné ou quelques autres problèmes quand je la fait en papier, en l'annulant je prends la facture papier suivante 00082 pour la remplir en marquant juste annulation sur la précédente. Dans le cas du logiciel si j'ai validé la facturation 00081 également par erreur et que je veux annuler celle-ci, alors l'avoir prends le numéro suivant 00082 de facture et la prochaine facture est incrémenté de 2 (00083)). 
Cela m'oblige à re-assigner le numéro de début de fichier de facturation pour coller avec mon fichier papier. 

En ce qui concerne le fait de tenir 2 systèmes, quand je n'ai pas l'email des patients, il m'est plus aisé de rendre une facture papier pour le moment. C'est le système que j'ai depuis le début et je n'ai pas encore basculé au système électronique exclusif. Mon fichier principal reste mon fichier papier par rapport au problème expliqué plus haut. Le système du logiciel reste un test pour moi car je n'envoi pour le moment aucune facture électroniquement et je suis du même avis que vous je ne sait pas si c'est légal de laisser chevaucher les deux systèmes. C'est également pas du tout pratique de tenir les deux. 

Quoiqu'il en soit ne pensez-vous pas qu'il serait plus pratique de séparer la numérotation des factures de celles des avoirs ? La comptabilité resterait équilibrée et le fichier facture des patients serait plus pratique à suivre (en prenant note que dans mon cas la majorité de mes annulations sont dû à une erreur dans le remplissage et pas forcément à une demande de remboursement).
