### ISSUE TITLE
Upgrade Django framework to 2.X version

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#212]
Django 1.11 is obsolete and unsecure now. 
The product has to be upgraded.

**Comment by JocelynDelalande** [comment]
Django is about to be absolete (April 2020), according to 

![image](https://user-images.githubusercontent.com/429633/79007103-c627ed80-7b5a-11ea-8836-543a7c90d966.png)

What about sticking on LTS release (maybe that was already your strategy :-)) ? Current LTS is 2.2.

**Comment by jbgury** [comment]
Thank you for the roadmap. YES the idea is to switch on LTS, so the closest is 2.2 version

**Comment by jbgury** [comment]
managed with PR #234
