### ISSUE TITLE
AIde à la saisie code postal / ville

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#216]
Dans la fiche patient

Avoir une auto-complétion à la saisie du code postal qui offre une liste déroulante de villes correspondant à ce code postal, permettant de remplir le champ ville sans erreur possible et avec un minimum d'erreur.

:birthday: :kiwi_fruit:

(je veux bien m'en charger)

**Comment by jbgury** [comment]
Merci pour cette proposition :+1: , en revanche, serait il possible de : 
 - soit pouvoir charger une liste de code postaux ? 
 - soit désactiver la fonction (le logiciel est utilisé au Canade et nouvelle Calédonie... Il n'y a pas de numéro Adéli ou SIRET/SIREN mais des identifiants s'y rapprochant...) En revanche les codes postaux ne seront jamais corrects.

_Edit :_ 
Je viens de voir que la commande existe pour charger une liste de codes postaux/ville :+1:

**Comment by JocelynDelalande** [comment]
Salut,

> Merci pour cette proposition +1 , en revanche, serait il possible de :
> 
>     * soit pouvoir charger une liste de code postaux ?

Il y a une commande, mais en l'état ça charge tous les codes postaux français, ni plus ni moins. Charger une liste de code postaux d'un autre pays demanderait d'avoir un fichier qui soit :

- accessible sur le web, 
- avec la même nomenclature exactement. 

… Peu probable.

>     * soit désactiver la fonction (le logiciel est utilisé au Canade et nouvelle Calédonie... Il n'y a pas de numéro Adéli ou SIRET/SIREN mais des identifiants s'y rapprochant...) En revanche les codes postaux ne seront jamais corrects.

Ah ok j'ignorais qu'il y avait des utilisateurices hors france :).

Le modèle actuel pourrait être étendu pour d'autres pays, mais ça demanderait pas mal d'adaptations (format et signification du « zipcode » numéro), probablement un peu cas par cas pour les pays concernés.

Pour l'heure, l'idée de rendre ça désactivable via une setting me semblerait la voie atteignable rapidement et pas trop sale.

@jbgury ça te semble raisonnable que ça soit activé par défaut ? (dans l'idée qu'une grande majorité d'utilisateur·ice·s exercent en france actuellement).

À terme, peut-être un paramètre « pays d'exercice » ?

**Comment by JocelynDelalande** [comment]
@jbgury j'avais une autre question : je me suis permis de créer une nouvelle app django (meilleure séparation), mais je craignais un peu d'aller contre le choix que tu avais fait de faire une seule app django. C'est OK pour toi ?

Est-ce que ça te va ?

**Comment by JocelynDelalande** [comment]
Petite vidéo du fonctionnement de la fonctionalité  (désolé, c'est du GIF un peu crado, github ne supporte pas la vidéo).

![Capture d’écran vidéo de 17-04-2020 22_02_13](https://user-images.githubusercontent.com/429633/79609716-85e6e300-80f7-11ea-8706-05b7500a734e.gif)

**Comment by jbgury** [comment]
Oui j'ai laissé les deux options, mais effectivement rendre la fonctionnalité paramétrable et active par défaut me semble très bien :)
Bravo pour cela, et parfait d'avoir créé une app pour cela. C'est vraiment une très belle réponse fonctionnelle que tu donnes là, merci à toi !

**Comment by JocelynDelalande** [comment]
Option est désactivable par paramètre utilisateur :

![image](https://user-images.githubusercontent.com/429633/79630411-582e8800-8151-11ea-9746-e5eaf857eafa.png)

**Comment by littlejo** [comment]
Pas mal... Est-ce qu'il n'y aurait pas moyen de proposer au début de la saisie les villes déjà enregistrées ?

**Comment by JocelynDelalande** [comment]
@littlejo C'est une très bonne idée… Que j'implémenterais peut-être plus tard car j'ai passé assez de temps sur cette feature pour l'instant :) 

En l'état actuel du code, taper quelques  lettres du nom de la ville à la suite du code postal devraient permettre une saisie déjà bien rapide.

**Comment by jbgury** [comment]
This first part is merged into develop.
Missing the part : propose already city input in first.

**Comment by JocelynDelalande** [comment]
Ménage d'automne :broom: 🍂 !

@jbgury J'ai créé #238 pour clarifier ce qui manque plutôt que de laisser ce ticket ouvert. N'hésite pas à le rajouter à la bonne milestone si nécessaire. Je ferme le présent ticket qui n'est plus nécessaire.

**Comment by jbgury** [comment]
:+1:
