### ISSUE TITLE
Passer le site vitrine sur un vrai nom de domaine.

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#223]
(pour remplacer le .github.io actuel)

Peut être vu comme un « petit pas » permettant de faciliter #221 .

Je veux bien prendre en charge la location du domaine pour 2 ans. En espérant que d'ici là on aie possibilité de faire reposer ce tout petit coût sur la communauté.

Mais je ne m'inquiète pas trop, j'ai vu plusieurs fois dans ce genre de cas des appels sur le bugtracker « qui veut payer pour le renouvellement du domaine » ; ça a toujours fonctionné.

Techniquement, le site peut [être sur un domaine propre et rester hébergé sur github.io](https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site).

**Comment by JocelynDelalande** [comment]
Mon point de départ à cette réflexion était le suivant : je suis en train de travailler sur le packaging appimage de libreosteo (#220), il faut indiquer un nom DNS pour l'identifiant de package, et je suis en train de me dire qu'indiquer `io.github.libreosteo` peut être assez enfermant pour la suite.

**Comment by jbgury** [comment]
J'ai acquis le domaine libreosteo.org, la migration se fera petit à petit (code à mettre à jour pour pointer sur les bonnes urls, et création du forum). 
Je ne crois pas qu'il soit possible avec github de desservir les pages depuis deux urls (ex: libreosteo.github.io et libreosteo.org)

**Comment by littlejo** [comment]
https://stackoverflow.com/questions/30167113/redirect-github-pages-to-custom-domain

**Comment by jbgury** [comment]
Thank you. Strange. When I tested, the domain libreosteo.github.io was not provided. I will test again…

**Comment by jbgury** [comment]
Je pense que le DNS n'était pas bien propagé lors de mes tests, ça a l'air de fonctionner à présent. La redirection est bien présente.

**Comment by littlejo** [comment]
Ok chez moi ça marche là

**Comment by jbgury** [comment]
Je dois corriger le produit, il y a un problème de support de la redirection :-1:

**Comment by JocelynDelalande** [comment]
Super, merci !
