### ISSUE TITLE
« LibreOsteo » ou « Libreosteo »

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#224]
Dans le README et sur https://libreosteo.github.io (et probablement dans les packages windows/mac) cohabitent les dénominations de « LibreOsteo » et « Libreosteo ».

Est-ce qu'on essaierait pas de retenir une casse « officielle » pour le nom.

J'ai une petite préférence pour « LibreOsteo » : plus graphique et lisible. Mais en vrai, ce qui m'importe est surtout qu'on soit cohérent·e·s :-).

Une fois que l'on est décidés, je peux me charger d'harmoniser.

**Comment by jbgury** [comment]
Pour ma part, je suis revenu à quelque chose de simple, et libreosteo me va très bien :D, du coup Libreosteo semble être satisfaisant.
Je pense qu'à la création moi-même je n'en étais pas certain de ce nom :)

**Comment by jbgury** [comment]
Je lance un sondage auprès des utilisateurs pour leurs avis sur le sujet :)

**Comment by jbgury** [comment]
https://framaforms.org/nom-du-logiciel-libreosteo-1603380119

**Comment by jbgury** [comment]
![Screenshot_20201111-113928_Firefox](https://user-images.githubusercontent.com/236368/98801902-cf3fac80-2412-11eb-8bf7-c507161de897.jpg)

Le résultat est assez clair, je vais faire les changements correspondant du coup
