### ISSUE TITLE
Récupérer l'archive via CLI

### ISSUE THREAD

**Issue by githubf-tfr** [libreosteo/LibreOsteo#241]
Je ne suis pas développeur mais pauvre ingénieur réseau :D, désolé donc pour les bêtises que j'écris niveau code !

J'ai une version sur raspberry chez moi, et j'avais besoin de récupérer l'archive de la base de donnée en CLI.
J'ai donc ajouté un fichier backup.py dans libreosteoweb/management/commands (ce n'est que du copier/coller de code déjà existant dans DbDump)
En faisant "python manage.py backup" on récupère l'archive "restore.db" directement sous "Libreosteo"

Voici le "backup.py" :
"
from django.core.management.base import BaseCommand, CommandError
from django.core.management import call_command 
from libreosteoweb import models
import zipfile
import sys
if sys.version_info.major == 2:
    from io import BytesIO
    from io import BytesIO as StringIO
else :
    from io import BytesIO,StringIO

class Command(BaseCommand):
    help = 'Make restore.db by CLI'

    def handle(self, *args, **options):
        
        zf = zipfile.ZipFile('restore.db', "w")

        buf = StringIO()
        call_command('dumpdata',
                     exclude=['contenttypes', 'admin', 'auth.Permission'],
                     stdout=buf)
        buf.seek(0)
        zf.writestr('dump.json', buf.getvalue())
        documents = models.Document.objects.all()
        for document in documents:
            zf.write(document.document_file.path, document.document_file.name)

        zf.close()
"

Si ça peut aider :D

**Comment by jbgury** [comment]
Très bonne chose ceci, je prépare une PR pour intégrer la modification ! Merci pour l'idée :+1:
