### ISSUE TITLE
[Consultation] Renommer le type de la consultation "Retour non prévu" en "Retour"

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#25]
Renommer : 
- "Retour non prévu" en "Retour"
- "Retour prévu (Contrôle)" en "Poursuite de traitement"

Un retour doit être réservé pour les séances qui n'ont pas porté leur fruit et doivent être remontés sur le tableau de bord en "rouge".

Les retours prévus sont des poursuites de traitement et non rien d'anormal sur l'activité du thérapeute.

L'objectif des retour est d'identifier une fatigue du thérapeute et donc une perte d'efficacité du traitement.

**Comment by libreosteo** [comment]
Fixed with the commit 5c805a6
