### ISSUE TITLE
Change title for invoice when displaying in the browser : year-month-day-invoice_number

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#263]
In order to have a usefull name when downloading or printing in pdf the invoice, it should be usefull to have the year-month-day-invoice_number into the name.

In order to have this, the title of the template has to be changed with YYYY-MM-DD-XXXXXX
where YYYY-MM-DD is the Year Month Day of the invoicing day, and XXXXXX is the invoice number

**Comment by Dalcim972** [comment]
Can i suggest to add the patient full name into the invoice title while you planning to change with date and number. 
Every time i rename the title i use : Facture number_Lastname_Firstname_YYYY-MM-DD. You can't tell me what u think about it. 
Thank you for your work.

**Comment by jbgury** [comment]
Yes sure, good idea !
