### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by githubf-tfr** [libreosteo/LibreOsteo#270]
Bonjour et merci pour le travail !

J'ai eu un problème qui m'a forcé à tout réinstaller mais j'ai tout de même pu faire une archive avant.

Le problème est que la ré-installation ne fonctionne pas (le serveur se lance mais l'archive ne prend pas, cela tourne dans le vide) :

- J'ai essayé sur deux architectures différentes (ARM64/AMD64), à chaque fois sur une ubuntu
- J'ai essayé avec les deux bdd (postgres et squlite) pour les deux archi
- J'ai essayé avec l'installation classique et le docker (via make build/make run) pour les 2 bdd/2archi

J'ai donc eu peur d'une corruption de mon archive.
Mais en faisant un "docker pull libreosteo/libreosteo-http:latest", puis en lançant cette image manuellement, mon archive a parfaitement fonctionné (avec un AMD64, puisqu'il n'y a pas d'image ARM64 dispo)

J'avais également pu faire un extract des patients et des rendez-vous, le résultat est le même pour tous les cas de figure...
Je crée mon admin, ce qui marche, mais quand j'importe les patiens+rdv, cela tourne dans le vide.

Bref je sèche :)

P.S : le "make build" ne fonctionnait pas à cause du nodejs-npm qui n'est pas trouvé. J'ai donc du faire un "apk add nodejs npm" (sans "-") à la place et pour que cela fonctionne, déplacer le"WORKDIR /Libreosteo" au dessus de l'"pak add".

**Comment by jbgury** [comment]
Bonjour,

En effet la dernière version alpine a scindé le paquet nodejs et npm en deux, et non plus un meta paquet permettant d'installer les deux, deplus la version nodejs est passé en nodejs 15 et non nodejs 14 d'où la nécessité de définir le workdir avant l'installation de nodejs.
Merci pour la remontée d'information.

J'ai corrigé le build du master et les images  du repository dockerhub sont en cours de mise à jour.

Pour l'importation des données, pas sûr d'avoir compris. c'est une archive réalisée depuis LibreOsteo ou bien une archive externe? Ce ne sont pas les exports CSV ?
Si ce sont les archives réalisées depuis le logiciel, c'est avant de définir un compte admin qu'il faut charger l'archive.
Ensuite cela peut être assez long (suivant la taille de l'archive).
Les logs donnent quoi lors de la restauration ?

Le support de l'architecture ARM n'est pas prévu pour publier les images, mais il est possible de créer les images Docker correspondantes comme tu l'as fait.

**Comment by githubf-tfr** [comment]
Je vais me focaliser ici sur le problème d'installation.

L'image docker actuellement présente sur le dépôt fonctionne parfaitement (j'ai donc fait une archive locale ^^)
Depuis ce docker, je fais deux choses : 
-  une archive en .db
-  un export des patients + rdv

Après : 
- je supprime mon container
- je repars des sources (installation directe, pas docker).
- L'installation se passe correctement. 
- Je vais sur 127.0.0.1:8000 pour atterrir sur la page d'acceuil
- Cas n° 1 : restore de la base de donnée /aucune erreur détectée dans les logs/les comptes mdp ont bien pris/
  mais : les rendez-vous ne sont pas visibles sur la page d'acceuil et lorsque je vais sur une patient, la fiche est vide et le titre/nom est :
> {$ patient.family_name $} ({$ patient.original_name $}) {$ patient.first_name $}
 - Cas n°2 : je crée un admin et j'importe l'export patient fait précemment --> même résultat

pour terminer : lorsque je reprend mon archive d'image docker, et que je refais le même processus, tout fonctionne !

**Comment by githubf-tfr** [comment]
Dernière précision étrange : 
sur le libreosteo "corrompu", lorsque je fais un export des patients, celui-ci semble bon ...

**Comment by jbgury** [comment]
L'installation de Libreosteo depuis les sources semblent montrer que la partie client Javascript ne s'installe pas bien. Comme cela fonctionne depuis les dernières archives docker ou même sur github depuis l'intégration continue, je pense plutot que le problème vient bien de l'installation en local sur ta machine.
Tout doit se jouer avec la commande 
`yarn`

Afin de mieux comprendre ce qu'il manque, il serait sans doute intéressant d'ouvrir la console du navigateur (F12 sur Mozilla Firefox ou Google Chrome) et de reporter les erreurs affichées dans cette console.

**Comment by githubf-tfr** [comment]
Ce n'est pas pour dire "non c'est pas moi !" :D, mais j'ai fait mes tests sur une archi AMD64 dans des VM crées pour l'occasion (une ubuntu, l'autre debian).

Je te passe quelques fichiers txt de log : 
- quelques erreurs au niveau du pip mais n'empêche pas de continuer
- le yarn semble bon
- pas d'erreur affichée au niveau de la console serveur lorsque l'on fait un restore
- Par contre le debugger Mozilla affiche quelques erreurs en effet (que je te laisse analyser, cela commence à être top loin de mon domaine d'expertise). La première (celle du script django) apparait dès la page d'accueil (proposant la restauration ou la création d'un admin). La second, celle du gettext, apparaît une fois connecté. 
[mozilla_debugger.txt](https://github.com/libreosteo/LibreOsteo/files/6676571/mozilla_debugger.txt)
[pip.txt](https://github.com/libreosteo/LibreOsteo/files/6676572/pip.txt)
[restore.txt](https://github.com/libreosteo/LibreOsteo/files/6676573/restore.txt)
[yarn.txt](https://github.com/libreosteo/LibreOsteo/files/6676574/yarn.txt)

**Comment by jbgury** [comment]
Petite question puisque je vois les traces d'exécution et le lancement avec 
`python ./manage.py runserver`
Est-ce que tu utilises un "settings" propre pour toi ? (ou une surcharge local.py) ? Si oui, est ce que le mode debug est actif ?
Sinon, c'est la raison de l'échec. La cible d'exécution 'runserver' est pour du debug, pour une cible plus proche de la production il faut utiliser soit ./server.py et donc faire le collectstatic avant, soit utiliser uwsgi (et nginx pourquoi pas) comme dans le conteneur Docker.

**Comment by jbgury** [comment]
Ok j'ai mis à jour la doc, il manquait une étape dans la documentation mais réalisée dans les process de build d'intégration continue ou docker : 
`python ./manage.py compilejsi18n`

ça va résoudre ton problème.
