### ISSUE TITLE
Export Database 

### ISSUE THREAD

**Issue by Pulsar0** [libreosteo/Libreosteo#279]
Can't export .CSV file from one computer to an other, once file imported one the new device, the "import" button won't be able to click on it.

**Comment by jbgury** [comment]
Not clear about the request... CSV export is available to download all data about examination and patient and to use for reintegration into an other system. In other words, open data to leave LibreOsteo (it is not a closed and proprietary software, you want to leave, you can, and you retrieve all data). 
It is not a feature to reimport data into LibreOsteo.

For this feature, you have to use "Archive" and Restore.
![image](https://user-images.githubusercontent.com/236368/152361941-1de66b5b-e642-4331-a916-28d73f059665.png)


Restore the archive could be only done on a fresh installation of LibreOsteo. 
Is your request to restore an archive at any time and so "scratch" all current data and replace by an archive ?
