### ISSUE TITLE
Add job in the indexation for Patient

### ISSUE THREAD

**Issue by jbgury** [libreosteo/Libreosteo#285]
Simple add the job field in the indexation in order to have the ability to find patient per job.
Simple feature, sometime could be practical.
With homonyms, search by adding some keyword for the search and job could help for the difference.

**Comment by DamyanBG** [comment]
Hello, I can work on that, please, assign it to me.

**Comment by DamyanBG** [comment]
Hi again,

I am not familiar with Angular, so I will unassign the task. I will follow the issue to see the solution.

**Comment by jbgury** [comment]
Hi,
Nothing with Angular for this part :) it is indexing data with whoosh component. But if you think that it is not possible no problem!
Thank you to try

**Comment by DamyanBG** [comment]
Hello,

I didn't said that it is not possible, I just not have experience with haystack and whoosh :) Now with your answer I found how to make it :)

**Comment by jbgury** [comment]
Basic testing : 
1. fill job on Patient file.
1. search on this job
2. Results should contain your link to the patient file
