### ISSUE TITLE
Export patients/examinations non conformes

### ISSUE THREAD

**Issue by githubf-tfr** [libreosteo/Libreosteo#287]
Bonjour,

J'essaie de récupérer un export de mes patients et de mes rendez-vous pour les réinjecter dans une instance totalement vierge et propre.
Après un premier travail pour faire correspondre les numéros patients avec leurs rendez-vous, j'essaie de les ré-injecter dans ma nouvelle instance sans succès.

J'ai modifié quelques éléments (car l'export sortait en anglais) comme la colonne R/L pour la transformer en G/D (comme indiqué dans le template d'import) mais sans plus de succès...

Avez-vous déjà tenté ce genre de manip ? Est-ce censé fonctionner ?

Merci pour votre aide !

**Comment by jbgury** [comment]
Bonjour,
Ce n'est pas du tout l'objet de cet export. Et il est volontairement non compatible, car l'export est destiné à un système externe (un autre logiciel). Le cas d'usage typique est : 
 - l'utilisateur veut quitter LibreOsteo pour un autre logiciel (propriétaire ou non), et peut récupérer l'ensemble de ces données dans un format lisible par la plupart des logiciels d'import de données.

La réimportation dans LibreOsteo de ce type de données est fortement déconseillé. Il n'y aura donc pas plus de support à ce titre.

De même l'import de données est destiné à recevoir des données d'un système externe (un autre produit) fournissant des données similaires.
