### ISSUE TITLE
Archive sqlite incompatible avec une instance postgres

### ISSUE THREAD

**Issue by githubf-tfr** [libreosteo/Libreosteo#288]
Bonjour,

J'ai essayé de migrer mon installation d'une instance sqllite vers une instance postgres (full docker).
Pour cela, je fais une archive que j'essaie d'injecter dans ma nouvelle installation.

Il m'indique que l'archive est corrompu.
Lorsque j'essaie avec une autre instance sqlite, tout fonctionne donc a priori, l'archive n'est pas totalement corrompu :)

Auriez-vous une idée ?

Merci beaucoup !

**Comment by jbgury** [comment]
Bonjour,
Serait il possible d'avoir plus d'information sur ce sujet ? (C'est une opération que je réalise fréquemment l'import de données SQLite vers un postgres).

Pourriez-vous : 
 - vérifier que les deux instances LibreOsteo sont exactement dans la même version ?
 - l'archive obtenue est bien dans le format YYYY-MM-DDTHH_MM_SS.XXXXX-libreosteo.db

Si ces conditions sont bien remplies, lors de la création de l'instance, et arrivé sur la page de création du compte administrateur, il est possible aussi de restaurer une archive, et c'est ici que l'on peut restaurer les données.

Est-ce bien la procédure que vous appliquez ?

**Comment by githubf-tfr** [comment]
La réponse est oui aux 3 questions :'( !

**Comment by jbgury** [comment]
Pourriez vous donner les messages de log s'il vous plaît : 
- les logs Docker du serveur Libreosteo

**Comment by githubf-tfr** [comment]
Bonjour,

avec (un peu) de retard :) : 


INFO 2023-01-14 13:06:04,320 views Load a dump from a sent file.
INFO 2023-01-14 13:06:04,320 views Load a dump from a sent file.
INFO 2023-01-14 13:06:04,378 views Dump file was persisted for future loading.
INFO 2023-01-14 13:06:04,378 views Dump file was persisted for future loading.
INFO 2023-01-14 13:06:04,379 views Signals were disactivated, perform clearing of the database
INFO 2023-01-14 13:06:04,379 views Signals were disactivated, perform clearing of the database
INFO 2023-01-14 13:06:04,616 views Execute query : BEGIN;
INFO 2023-01-14 13:06:04,616 views Execute query : BEGIN;
INFO 2023-01-14 13:06:04,617 views Execute query : SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), 1, false);
INFO 2023-01-14 13:06:04,617 views Execute query : SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), 1, false);
INFO 2023-01-14 13:06:04,620 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), 1, false);
INFO 2023-01-14 13:06:04,620 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), 1, false);
INFO 2023-01-14 13:06:04,622 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_group"','id'), 1, false);
INFO 2023-01-14 13:06:04,622 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_group"','id'), 1, false);
INFO 2023-01-14 13:06:04,624 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_group_permissions"','id'), 1, false);
INFO 2023-01-14 13:06:04,624 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_group_permissions"','id'), 1, false);
INFO 2023-01-14 13:06:04,627 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_user"','id'), 1, false);
INFO 2023-01-14 13:06:04,627 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_user"','id'), 1, false);
INFO 2023-01-14 13:06:04,629 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_user_groups"','id'), 1, false);
INFO 2023-01-14 13:06:04,629 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_user_groups"','id'), 1, false);
INFO 2023-01-14 13:06:04,631 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_user_user_permissions"','id'), 1, false);
INFO 2023-01-14 13:06:04,631 views Execute query : SELECT setval(pg_get_serial_sequence('"auth_user_user_permissions"','id'), 1, false);
INFO 2023-01-14 13:06:04,633 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_regulardoctor"','id'), 1, false);
INFO 2023-01-14 13:06:04,633 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_regulardoctor"','id'), 1, false);
INFO 2023-01-14 13:06:04,635 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_patient"','id'), 1, false);
INFO 2023-01-14 13:06:04,635 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_patient"','id'), 1, false);
INFO 2023-01-14 13:06:04,637 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_children"','id'), 1, false);
INFO 2023-01-14 13:06:04,637 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_children"','id'), 1, false);
INFO 2023-01-14 13:06:04,640 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_examination"','id'), 1, false);
INFO 2023-01-14 13:06:04,640 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_examination"','id'), 1, false);
INFO 2023-01-14 13:06:04,642 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_examination_invoices"','id'), 1, false);
INFO 2023-01-14 13:06:04,642 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_examination_invoices"','id'), 1, false);
INFO 2023-01-14 13:06:04,644 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_examinationcomment"','id'), 1, false);
INFO 2023-01-14 13:06:04,644 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_examinationcomment"','id'), 1, false);
INFO 2023-01-14 13:06:04,646 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_invoice"','id'), 1, false);
INFO 2023-01-14 13:06:04,646 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_invoice"','id'), 1, false);
INFO 2023-01-14 13:06:04,648 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_paimentmean"','id'), 1, false);
INFO 2023-01-14 13:06:04,648 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_paimentmean"','id'), 1, false);
INFO 2023-01-14 13:06:04,650 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_paiment"','id'), 1, false);
INFO 2023-01-14 13:06:04,650 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_paiment"','id'), 1, false);
INFO 2023-01-14 13:06:04,653 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_paiment_invoice"','id'), 1, false);
INFO 2023-01-14 13:06:04,653 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_paiment_invoice"','id'), 1, false);
INFO 2023-01-14 13:06:04,655 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_officeevent"','id'), 1, false);
INFO 2023-01-14 13:06:04,655 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_officeevent"','id'), 1, false);
INFO 2023-01-14 13:06:04,657 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_officesettings"','id'), 1, false);
INFO 2023-01-14 13:06:04,657 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_officesettings"','id'), 1, false);
INFO 2023-01-14 13:06:04,659 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_therapeutsettings"','id'), 1, false);
INFO 2023-01-14 13:06:04,659 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_therapeutsettings"','id'), 1, false);
INFO 2023-01-14 13:06:04,661 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_fileimport"','id'), 1, false);
INFO 2023-01-14 13:06:04,661 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_fileimport"','id'), 1, false);
INFO 2023-01-14 13:06:04,664 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_document"','id'), 1, false);
INFO 2023-01-14 13:06:04,664 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_document"','id'), 1, false);
INFO 2023-01-14 13:06:04,666 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_loggedinuser"','id'), 1, false);
INFO 2023-01-14 13:06:04,666 views Execute query : SELECT setval(pg_get_serial_sequence('"libreosteoweb_loggedinuser"','id'), 1, false);
INFO 2023-01-14 13:06:04,668 views Execute query : SELECT setval(pg_get_serial_sequence('"zipcode_lookup_zipcodemapping"','id'), 1, false);
INFO 2023-01-14 13:06:04,668 views Execute query : SELECT setval(pg_get_serial_sequence('"zipcode_lookup_zipcodemapping"','id'), 1, false);
INFO 2023-01-14 13:06:04,670 views Execute query :
INFO 2023-01-14 13:06:04,670 views Execute query :
ERROR 2023-01-14 13:06:04,672 views Import failed
Traceback (most recent call last):
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: can't execute an empty query

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Libreosteo/./libreosteoweb/api/views.py", line 785, in post
    cursor.execute(s)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute
    with self.db.wrap_database_errors:
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: can't execute an empty query
ERROR 2023-01-14 13:06:04,672 views Import failed
Traceback (most recent call last):
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: can't execute an empty query

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Libreosteo/./libreosteoweb/api/views.py", line 785, in post
    cursor.execute(s)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute
    with self.db.wrap_database_errors:
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Libreosteo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: can't execute an empty query
[pid: 9|app: 0|req: 6/29] 192.168.1.10 () {50 vars in 1018 bytes} [Sat Jan 14 13:06:04 2023] POST /internal/restore => generated 70 bytes in 580 msecs (HTTP/1.1 412) 5 headers in 178 bytes (73 switches on core 0)

**Comment by jbgury** [comment]
L'erreur est étrange... est ce une image Docker que vous avez créé à partir des sources ?

**Comment by jbgury** [comment]
Ok compris... Votre image est bien trop ancienne, soit mettez à jour l'image Libreosteo, soit mettez à jour votre code, cette erreur a été corrigée le 9 juin 2022 (voir  : https://github.com/libreosteo/LibreOsteo/commit/d7da19d80a779cb03afbd91f46598d5803fb830f ) 
Je regénère l'image Docker car elle semble dater d'avant : 
![Capture d’écran de 2023-01-14 14-52-57](https://user-images.githubusercontent.com/236368/212475371-51517e15-4eb8-4c5e-a7e2-0c0998c619d3.png)

**Comment by jbgury** [comment]
L'image est à jour sur le Hub docker à présent

**Comment by githubf-tfr** [comment]
Merci en effet ça marche (je reconstruis l'image car je suis en arm64)
J'ai d'autres bugs mais je ferai un autre sujet :)
Bon weekend !

**Comment by jbgury** [comment]
Les images seront à présent publiées en arm64, arm-v7, amd64

**Comment by githubf-tfr** [comment]
Super !! Ca va bien me faciliter la vie ! XD

**Comment by githubf-tfr** [comment]
Bonjour,

L'image libreosteo/libreosteo-http est bien disponible en arm64 mais pas libreosteo/libreosteo-pg. 
Est-ce normal ?
