### ISSUE TITLE
make a name form field mandatory

### ISSUE THREAD

**Issue by land22** [libreosteo/Libreosteo#294]
how can I modify your application so that when a new patient is created, the "date of birth" field is not mandatory.
I've done this in the model that concerns the patient and in the form, but it hasn't changed anything. Please help me

Regards

**Comment by jbgury** [comment]
What is the request ? Why removing the birth date of the creation ? It is risky operation to have duplicate entry in the database.
In this case, a merging function have to be implemented. The easier is to let the birth date mandatory.

Moreover with the title of the issue-, I don't understand exacltly the expected requirement. Sorry.

**Comment by land22** [comment]
> What is the request ? Why removing the birth date of the creation ? It is risky operation to have duplicate entry in the database. In this case, a merging function have to be implemented. The easier is to let the birth date mandatory.
> 
> Moreover with the title of the issue-, I don't understand exacltly the expected requirement. Sorry.

Hello and thank you for your reply. Perhaps I misspoke.
In the form for adding a patient, I want to make the date of birth field optional, not compulsory.  I did this in the model 
`class Patient(models.Model):
    birth_date = models.DateField(_('Birth date'), blank=True, null=True)`
but it didn't change anything. when I fill in the form for a new patient, it says that the date of birth field is compulsory. Pls how can change it
Regards

**Comment by jbgury** [comment]
I think it is a bad idea to remove the birth date of the key of patient. Homonyme is frequent, and birth date is discriminent. To avoid duplicate entry of patients, it disallow to input the same name/firstname patient file with the same birth date.
It is not perfect but statistically rare.

**Comment by land22** [comment]
Hello @jbgury ,
Thank you for your message,
I understand, but it's just the customer's requirements. And the aim is to make this alternative and not compulsory.
Best regards,

**Comment by jbgury** [comment]
Even if customer wants it, it does not mean that it is a good idea. Indeed, when there were lot of duplication of patient in the system with differents examination for the same patient but dispatched in different files, it will be useless. In the general system to identify people : Name, firstname and birthdate are the minimum information to identify someone. I don't recommand to make the birth date optional
