### ISSUE TITLE
Chargement sur McOS Séquoia 15.1.1

### ISSUE THREAD

**Issue by GeoffroyCurie** [libreosteo/Libreosteo#307]
Bonjour,
le logiciel librosteo m'a été vivement recommandé hélas je ne peux pas le charger sur mon Mac avec l'Os Séquoia.
Avez-vous des conseils pour que je puisse l'installer ?

Bien à vous

**Comment by jbgury** [comment]
Bonjour suivre les conseils d'installation des pages supports https://github.com/libreosteo/LibreOsteo/wiki/Installation_Macosx
