### ISSUE TITLE
Numéro Siret Cabinet/Utilisateur

### ISSUE THREAD

**Issue by GitNitneroc** [libreosteo/LibreOsteo#31]
Le numéro SIRET est attribué au cabinet, et pas aux utilisateurs, alors que chaque utilisateur aura un n° différent

**Comment by libreosteo** [comment]
Excellente remarque et merci pour ce rapport d'anomalie fonctionnelle.

**Comment by GitNitneroc** [comment]
En fait le problème est peut être un peu plus large que le cas du Siret. 
Je n'ai pas regardé encore dans le détail, mais plusieurs autres choses sont gérées à l'échelle du cabinet (et donc non modifiables par/pour chaque utilisateur), je pense par exemple aux en-têtes de factures, montants etc...

**Comment by libreosteo** [comment]
Tout dépend de l'orientation prise autour de Libreosteo, doit il gérer un seul cabinet par instance ou bien plusieurs cabinets par instance ?
Pour le moment, le choix a été délibérement de gérer un cabinet par instance, pour différents cabinets il faudra donc plusieurs instances de libreosteo. La base patient reste spécifique à un cabinet. Par contre les utilisateurs sont des thérapeutes au sein de ce cabinet, et peuvent se partager les patients. 
La question : est il logique d'avoir des montants différents au sein d'un même cabinet ? 
L'entête de facture désigne le cabinet, ensuite le thérapeute est attaché à ce cabinet même s'il y travaille à son compte.
Pour le siret je vois bien, mais pour l'adresse du cabinet et les montants par exemple, j'aimerais comprendre pourquoi chaque utilisateur devrait pouvoir les modifier
As tu des exemples sur ce sujet ?

**Comment by GitNitneroc** [comment]
Tout à fait d'accord sur la direction 1 instance = 1 cabinet. Par contre il y a plusieurs thérapeutes, et même s'ils ont la même adresse certains peuvent avoir des associations de gestion différentes, et certains le font figurer sur les factures. Pour le montant des soins, je ne sais pas si c'est logique ou pas, mais ça se fait dans plusieurs cabinets de ma connaissance. 

Je repense au Siret : je ne l'ai jamais fait figurer sur mes factures, sans que ça pose problème, et je ne suis pas sûr que ce soit problématique.

**Comment by libreosteo** [comment]
Je vois pour les associations de gestion. En effet, je comprends à présent la problématique qui n'avait pas été remontée jusqu'à présent. Ensuite le montant est mis par défaut sur le cabinet, au moment de la facturation du patient, le thérapeute est libre d'y spécifier le montant à facturer (et donc affiché sur la facture).
Concernant le siret, il me semble que pour une facture c'est obligatoire, pour une note d'honoraire c'est peut être différent. Il y a justement l'issue #29 qui devrait permette de corriger ceci. Je dois encore définir un peu plus cette fonction avant de l'implémenter.
