### ISSUE TITLE
Module Comptabilité

### ISSUE THREAD

**Issue by GitNitneroc** [libreosteo/LibreOsteo#32]
Je ne sais pas quels sont les projets pour Libreosteo, mais il me semble que la suite ne sera réellement fonctionnelle que quand une partie comptabilité sera ajoutée. Ca peut être assez simple : 
Résumé des séances facturées, des paiements en attentes etc...

Dans l'idéal,p uisqu'il y a un module pour les stats et graphs, une évolution du nombre de séances (par utilisateur et pour le cabinet), ainsi que des montants facturés par mois, années etc...

Je pensais pouvoir éventuellement participer au développement, mais rien qu'à installer Libreosteo sur pythonanywhere, je me rends compte que mes souvenirs de django remontent à bien longtemps :D

**Comment by libreosteo** [comment]
C'est l'essence de libreosteo de pouvoir fournir ce type d'informations et depuis longtemps un réel souhait de le faire. Pourquoi ce n'est pas fait encore ? Par manque de temps dans un premier temps et par manque de soutien dans un second temps. Peu de contributions, peu de retour, j'ai passé plus de temps à faire connaître libreosteo qu'à l'améliorer sur ces derniers mois.
Tes contributions me font donc plaisir, et surtout booste l'évolution de libreosteo. Et pour cela je t'en remercie. 
A présent, la prochaine version de Libreosteo devrait contenir ce module car il est temps de le faire évoluer.

**Comment by GitNitneroc** [comment]
C'était évidemment une suggestion pour le futur et pas un reproche. Je trouve LibreOsteo très séduisant sur bien des points, et c'est presque déjà utilisable pour moi. La prochaine version devrait donc me permettre d'utiliser au quotidien LibreOsteo. 

Merci pour ton travail, je verrai petit à petit si je suis capable de donner un coup de pouce au développement

**Comment by libreosteo** [comment]
Pas du tout pris pour un reproche :) 
et ça me fait plaisir de voir que ce travail intéresse. Je suis curieux de connaître le nombre d'utilisateur de ce logiciel :).

**Comment by libreosteo** [comment]
Juste une question @GitNitneroc, comment as tu connu libreosteo ? As tu eu des difficultés à déployer sur pythonanywhere ou autre ? Car la documentation est encore manquante sur ce sujet.
merci bien pour ton retour

**Comment by GitNitneroc** [comment]
Je crois être tombé sur un lien dans un wiki ou un forum (je n'arrive pas à retrouver où, dsl)... Je recherchais des logiciels de gestion de cabinet d'ostéo, et je suis tombé sur freemedforms et quelques autres avant de tomber sur Libreosteo. L'approche web est un vrai plus pour moi, puisque je recherchais justement ce logiciel dans le cadre de l'ouverture d'un second cabinet, l'accès à distance est donc un plus non négligeable.

**Comment by GitNitneroc** [comment]
Pour ce qui est des difficultés d'installation, ça vient surtout de mes connaissances imparfaites de ces environnements. Voici ce qui m'a posé problème, lors de mon installation sur pythonanywhere avec python 2.7.6 : 
après un git clone, je n'avais pas compris que l'installation de packages python allait avoir besoin de l'argument --user dans pythonanywhere : 
    pip install --user module
Du coup j'ai eu plein de messages d'erreurs que je n'ai compris que lorsque j'ai vu qu'il me manquait djangorestframework alors que c'était sensé être installé.

Même après avoir refait cette manip correctement, il me semble que cx_freeze m'a fait des erreurs, mais si ma mémoire est bonne (je n'ai plus fait de python depuis des années) cx_freeze sert à faire des exécutables donc j'ai imaginé que ce n'était pas bien grave et que tu t'en servais uniquement pour pouvoir fournir une version windows/macOS exécutable.

Après j'ai encore eu des problèmes directement liés à pythonanywhere : on ne peut pas faire le runserver, et j'ai donc du créer une web app, refaire le wsgi et je pensais que ce serait bon.

Seulement le chemin des templates n'était pas bon, j'ai directement modifié ça dans les settings : il cherchait à "/templates" et j'ai remplacé par "/Libreosteo/templates" pour ne plus avoir l'erreur des templates introuvables. J'ai ensuite eu le même problème pour tous les fichiers statics... Là encore j'ai mis l'adresse entière dans STATIC_ROOT, j'ai refait un collectstatic et changé dans les options de pythonanywhere les options de static files en donnant l'url et le chemin. Depuis tout semble fonctionner correctement, mais je suis sûr qu'il y aurait eu une solution plus simple qui aurait modifié à la fois le chemin des templates et des statics, mais je n'ai pas trouvé.

Je suis prêt à refaire une install plus propre si tu as des conseils ! Je n'utilise pas libreosteo professionnellement pour l'instant, donc je peux tout me permettre.

**Comment by libreosteo** [comment]
@GitNitneroc  pour le déploiement sur pythonanywhere j'ai fais une ébauche de ce qu'il faudrait faire. Si ça peut t'aider. Normalement il y a plus simple que ce que tu as fais, mais non documenté.... il fallait le savoir...
Voir issue #34

**Comment by GitNitneroc** [comment]
Merci ! Belle réactivité ! Je referai l'install pour tester ça et je me permettrai quelques questions si je bute sur certains points.

**Comment by jbgury** [comment]
Un module comptabilité étant initié, je ferme ce ticket .
