### ISSUE TITLE
Déploiement WEB de Libreosteo

### ISSUE THREAD

**Issue by libreosteo** [libreosteo/LibreOsteo#34]
Le déploiement d'une version hébergée de Libreosteo n'est pas documentée. Voici une ébauche de procédure à travers cette issue qui reste à être complétée.

**Comment by libreosteo** [comment]
voir la procédure : 
https://github.com/libreosteo/Libreosteo/wiki/D%C3%A9ploiement-sur-pythonanywhere

**Comment by libreosteo** [comment]
Le mode utilisé est le mode démonstration. Le changement de mot de passe est impossible sur la page des utilisateurs en administrateur dans ce mode. Il faut donc modifier dans le fichier : 
`Libreosteo/settings/demonstration.py`  la variable DEMONSTRATION est mettre : 
`DEMONSTRATION = False`

**Comment by libreosteo** [comment]
Ajout de la décharge de responsabilité sur la page WIKI, il est de la responsabilité de l'utilisateur de Libreosteo d'assurer la sécurité des échanges entre le navigateur et le serveur en installant au minimum un certificat SSL et changeant la variable SECRET

**Comment by GitNitneroc** [comment]
Je viens de tenter le processus décrit dans le wiki. J'ai une erreur lors de l'installation de wsgiref, via pip.

Je n'ai pas trop eu le temps d'investiguer

**Comment by libreosteo** [comment]
En effet, je pense que python3 n'est pas correctement supporté par la version de wsgiref. 
Refaire l'install de l'environnement virtualenv sans préciser la version de python en paramètre de mkvirtualenv. Je créé une issue sur ce sujet pour le support python3.

**Comment by GitNitneroc** [comment]
Je retenterai avec python 2.7

**Comment by nicosteo** [comment]
Si quelqu'un a avancé sur ce sujet ce serait super, car la c'est compliqué pour moi ...

**Comment by jbgury** [comment]
Vous avez tenté de suivre la procédure ? Des étapes vous sont elles peu claires ? Le niveau est en effet plus technique, si vous le souhaitez un accompagnement peut être possible sur ce sujet. Mais la réalisation par vous même devrait être possible sur un environnement tel que pythonanywhere. Cela dit si des points sont peu clairs dans la réalisation, on peut compléter.

**Comment by nicosteo** [comment]
Bonsoir, oui malgré d'assez bonnes notions de bidouillage en tout genre :D, la c'est du code pur et dur et c'est un peu au dessus de mes capacités je crois :S

**Comment by jbgury** [comment]
Bonjour, quand vous dites du code pur et dur, vous parlez de la procédure dans le wiki ? Sur quelles étapes avez vous peiné ? quels sont les problèmes que vous avez rencontré sur pythonanywhere ? Je vais revoir certaines parties dans les semaines à venir pour expliciter certains points de la procédure alors

**Comment by jbgury** [comment]
Bonjour à tous les deux,

Vous en êtes où sur ces sujets ? Quels sont les points qui vous bloquent dans la procédure ?

**Comment by GitNitneroc** [comment]
Désolé de ne pas être revenu plus tôt pour commenter ici...

Je viens de refaire une nouvelle installation sur pythonanywhere, avec python 2.7, et je n'ai pas réussi à faire fonctionner le tout. J'arrive sur une erreur interne 500.

Je n'ai pas d'énorme erreur lors de la procédure, quelques petits warnings par rapport à des versions, mais sans importance je pense. Le seul indice que j'ai, c'est que ce qui touche à la bdd semble poser problème : lors du "manage.py migrate" j'ai une erreur comme quoi il manque une table, appellée libreosteoweb_fileimport

et dans mes erreurs de serveur je n'ai pas de stacktrace complète, mais ça semble s'orienter vers des problèmes de sqlite : 

> 2016-08-29 22:31:06 ERROR Internal Server Error: /#012Traceback (most recent call last):#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response#012    response = middleware_method(request)#012  File "/home/osteo/Libreosteo/libreosteoweb/middleware.py", line 46, in process_request#012    if UserModel.objects.all().count() == 0 :#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count#012    return self.query.get_count(using=self.db)#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 464, in get_count#012    number = obj.get_aggregation(using, ['__count'])['__count']#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 445, in get_aggregation#012    result = compiler.execute_sql(SINGLE)#012  File "/home
> 2016-08-29 22:31:07 announcing my loyalty to the Emperor...
> 2016-08-29 22:31:10 ERROR Internal Server Error: /#012Traceback (most recent call last):#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response#012    response = middleware_method(request)#012  File "/home/osteo/Libreosteo/libreosteoweb/middleware.py", line 46, in process_request#012    if UserModel.objects.all().count() == 0 :#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count#012    return self.query.get_count(using=self.db)#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 464, in get_count#012    number = obj.get_aggregation(using, ['__count'])['__count']#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 445, in get_aggregation#012    result = compiler.execute_sql(SINGLE)#012  File "/home
> 2016-08-29 22:31:11 ERROR Internal Server Error: /favicon.ico#012Traceback (most recent call last):#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response#012    response = middleware_method(request)#012  File "/home/osteo/Libreosteo/libreosteoweb/middleware.py", line 46, in process_request#012    if UserModel.objects.all().count() == 0 :#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count#012    return self.query.get_count(using=self.db)#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 464, in get_count#012    number = obj.get_aggregation(using, ['__count'])['__count']#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 445, in get_aggregation#012    result = compiler.execute_sql(SINGLE)#012  

je ne sais pas si ça peut aider au diagnostic, mais si je fais un python -i /var/www/monsite_pythonanywhere_com_wsgi.py  je retombe encore sur ce problème de table manquante : 

> ERROR Exception when purging files at starting application
> Traceback (most recent call last):
>   File "/home/osteo/Libreosteo/libreosteoweb/apps.py", line 17, in ready
>     for f in file_import_list:
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in **iter**
>     self._fetch_all()
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
>     self._result_cache = list(self.iterator())
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
>     results = compiler.execute_sql()
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
>     return Database.Cursor.execute(self, query, params)
> OperationalError: no such table: libreosteoweb_fileimport

Ca n'a peut-être aucun rapport, mais dans la racine de mon projet (/home/monsite/) un db.sqlite3 de 0octets qui est créé. Et j'en ai un second de taille plus correcte dans /home/monsite/Libreosteo... 

D'avance, merci docteur

**Comment by jbgury** [comment]
En effet, il s'agit bien d'un problème de base de données. En fait, lors du déploiement, par défaut il est utilisé Libreosteo/settings/demonstration.py
Si on lance manage.py migrate sans préciser le settings, le fichier db.sqlite3 généré directement dans le répertoire ne sera pas celui utilisé par le middleware WSGI.

Pour réussir la migration, il faut préciser en paramètre le fichier en notation pointé, ce qui donne : 
`manage.py migrate --settings Libreosteo.settings.demonstration`

Le fichier à la racine ne sera plus à 0 octets, un rédemarrage de l'appli web devrait corriger le pb.

**Comment by GitNitneroc** [comment]
je n'ai d'abord, pas réussi, mais cette syntaxe : 
`python manage.py migrate --settings=Libreosteo.settings.demonstration`
 semble avoir réglé le problème : ma bdd a une taille normale maintenant.

Mais ce n'est pas réglé pour autant !

J'ai toujours une erreur 500, mais maintenant, je suis quand même redirigé vers la création d'admin (/accounts/create-admin/). Cette fois l'erreur semble venir d'un template ...?
`ERROR Internal Server Error: /accounts/create-admin/#012Traceback (most recent call last):#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response#012    response = response.render()#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render#012    self.content = self.rendered_content#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/template/response.py", line 133, in rendered_content#012    template = self._resolve_template(self.template_name)#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/template/response.py", line 88, in _resolve_template#012    new_template = self.resolve_template(template)#012  File "/home/osteo/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/django/template/response.py", line 80, in resolve_t`

Je me permettrai quelques modifs sur le wiki si j'arrive à venir à bout de la procédure

**Comment by jbgury** [comment]
Bonjour,
La syntaxe varie selon les versions django avec = ou sans.

Pour le pb sur la template si vous utilisez la dernière version il y a un
module supplémentaire django-compressor.
Il faut rassembler les données artifacts avec
Python manage.py collectstatic

Puis
python manage.py compress

Si ça ne résout pas activez debug sur template et système dans
Libreosteo/settings/demonstration.py

Je pourrai faire des verifs sur mes syntaxes ce soir. Je donne les
commandes de tête.

Merci à toi

Jean-Baptiste Gury

**Comment by GitNitneroc** [comment]
Je suis sur la version 0.5.2
J'ai donc installé django-compressor. Collectstatic a fonctionné mais pas manage.py compress : 
`Unknown command: 'compress'`
J'ai donc ajouté compress dans les installed_apps, mais compress n'est pas activé, du coup je me dis que je ne suis peut-être pas sur la bonne voie...

Mais de toutes façons activer les débugs montraient qu'il y avait un autre problème : le template n'était pas trouvé, et il ne cherchait effectivement pas au bon endroit : `Django tried loading these templates, in this order:
Using loader django.template.loaders.filesystem.Loader:
/home/osteo/templates/account/create_admin_account.html (File does not exist)
/home/osteo/static/account/create_admin_account.html (File does not exist)`

J'ai corrigé ça en changeant le working directory de l'onget Web de pythonanywhere. Je pensais que la source devait être mon dossier Libreosteo, mais que le working directory devait être mon espace perso /home/user/... Ce qui n'était clairement pas le cas.

Du coup ça semble fonctionenr

**Comment by jbgury** [comment]
oui pardon, il semble que django-compressor soit sur la branche de développement et non la branche stable....
Je suis désolé de tête je me suis trompé. concernant la configuration de l'application je crois que tu as trouvé, et cela semble bien ça. A compléter sur le wiki
Merci beaucoup pour ce travail en tout cas

**Comment by GitNitneroc** [comment]
Aucun problème. Je n'aurai pas le temps de compléter le wiki aujourd'hui, mais je compte bien m'y coller très vite, tant que c'est frais dans ma tête.

C'est à moi de te remercier pour le travail sur Libreosteo et pour ton aide.

**Comment by jbgury** [comment]
Sur ma configuration, le working directory est bien mon home par contre dans les configurations des static Files, j'y ai mis : 
URL : /static/
Directory : /home/user/Libreosteo/libreosteoweb/static

**Comment by GitNitneroc** [comment]
ok, je viens de modifier ma config pour faire comme toi, et ça fonctionne ici

EDIT : ah non, ça ne marche plus, je regarde ça

**Comment by GitNitneroc** [comment]
Bon, je n'ai plus trop le temps de regarder ce soir, mais ça pose des problèmes, les factures donnent des erreur 500 par exemple et la recherche de patients semble ne pas fonctionner.
j'investiguerai bientôt

**Comment by jbgury** [comment]
Erreur 500 uniquement sur les factures ?

**Comment by GitNitneroc** [comment]
Je crois que j'avais cette erreur 500 uniquement sur les factures quand j'ai essayé de modifier ma config avec le working directory et les static files là où tu les as mises.
Mais peut-être que je me suis trompé ou que j'ai raté quelquechose.
Je suis à peu près sûr que la recherche de patients ne marchait plus non plus, d'ailleurs.

**Comment by GitNitneroc** [comment]
Désolé de rouvrir une discussion qui a plus de 6 mois et qui aurait davantage sa place sur un forum que sur les issues...

J'ai une version 0.5.2 qui tourne parfaitement bien sur pythonanywhere. Je me disais qu'il serait peut-être temps de faire une mise à jour. Est-ce qu'il y a une procédure particulière à suivre ? je sauve le fichier sqlite et je désinstalle/réinstalle ?

merci d'avance

**Comment by jbgury** [comment]
Pour procéder à la mise à jour, il faut télécharger les sources évidemment décompresser, executer bower install, puis effectuer la migration de la base de données avec la commande vu au dessus 
`python manage.py migrate --settings Libreosteo.settings.demonstration` 
puis faire le collectstatic, la compression des templates. Je pense que tout ceci pourrait s'automatiser, mais il reste une chose à ne pas oublier.
Modifier le wsgi de pythonanywhere pour pointer vers le nouveau dossier des sources libreosteo (ne pas oublier la définition des static aussi !)

J'effectue toujours une sauvegarde de la base de données oui

**Comment by jbgury** [comment]
Comment se passe le déploiement web alors ? Encore des difficultés, des points bloquants ?
