### ISSUE TITLE
La saisie de date de naissance sous Chrome fonctionne mal

### ISSUE THREAD

**Issue by libreosteo** [libreosteo/LibreOsteo#37]
Difficulté de saisir une date de naissance pour un patient lors de l'ajout d'un nouveau patient.

**Comment by libreosteo** [comment]
La sélection de la date de naissance s'effectue à travers une boîte de dialogue, mais la saisie directe au clavier serait plus aisée.

**Comment by jbgury** [comment]
Corrigé dans la release 0.5
