### ISSUE TITLE
Multiples montants honoraires

### ISSUE THREAD

**Issue by nicosteo** [libreosteo/LibreOsteo#50]
Avoir la possibilité de choisir différents montants (Tarif enfant, Adulte, ...) dans les paramètres du cabinet et donc dans la facturation.

**Comment by jbgury** [comment]
Ce point a été demandé par plusieurs utilisateurs. Cela dit j'aimerais qu'il soit explicité pour permettre de l'implémenter. En effet : 
- lors de la facturation d'une consultation, vous pouvez changer le tarif de celle ci selon des règles qui vous sont propres. Le montant indiqué dans les paramétrages cabinet permet uniquement de pré-renseigner le montant.
- sur quels critères une consultation peut avoir différents tarifs ? Uniquement enfant/Adulte ? Dans ce cas, il est nécessaire d'y définir un âge limite qui devra donc être positionné dans le paramétrage cabinet pour les différents tarifs. Se peut-il que d'autres critères rentrent en compte ? Je n'ai pas encore assez d'infos remontées par les utilisateurs sur ce sujet : l'âge devra être bien précisé (car certains me diront pour des nourrissons, d'autes des enfants jusque 10ans, d'autres jusque 18 ans).

C'est la raison pour laquelle, le montant est libre d'être modifié au moment de la facturation. Mais on peut imaginer un fonctionnement à minima sur plusieurs tarifs au critère unique de l'âge dans un premier temps.

**Comment by GitNitneroc** [comment]
Pour moi, le montant libre à la facturation est suffisant : c'est la
solution la plus souple.

Il m'arrive de pratiquer des tarifs différents selon des critères que
LibreOsteo ne pourra jamais prendre en compte, comme des plus petites
séances de "dépannage" pour les urgences.
Le 10 févr. 2016 06:11, "Jean-Baptiste G." notifications@github.com a
écrit :

**Comment by nicosteo** [comment]
Je suis d'accord effectivement je pensais que la configuration était bloqué ensuite, je n'ai pas testé encore le logiciel de bout en bout, donc si libre une fois la facturation mis en place autant pour moi c'est parfait ! :D :+1:
