### ISSUE TITLE
Indiquer le nom du praticien sur la consultation

### ISSUE THREAD

**Issue by moullec** [libreosteo/LibreOsteo#53]
Le logiciel propose le multi-utilisateur avec la même base de donnée.
Lorsqu'un même patient est traité par plusieurs personnes en dans le cabinet (en cas de consultation faite par un remplaçant, assistant ou co-titulaire), on ne sait pas qui l'a pris en charge.

Pour avoir un meilleur suivi du patient il serait intéressant d'avoir le nom du thérapeute dans la page consultation lors de relectures ultérieurs.

**Comment by jbgury** [comment]
Dans la liste des consultations pour un patient, le nom du thérapeute est donné, il n'est en revanche pas rappelé lorsque la consultation est ouverte. 
Afin de couvrir cette demande, je propose de rajouter le nom du thérapeute dans l'entête de la consultation (là où il y a la date)
[Exemple de consultation avec nom du thérapeute dans la liste des consultations](http://garthylou.pythonanywhere.com/#/patient/108/examinations)

**Comment by moullec** [comment]
C'était effectivement mon idée. Merci beaucoup

**Comment by jbgury** [comment]
réalisé à travers le commit : 52bdb9509f944268c0a3e77d58ce2d8a15aecb50
