### ISSUE TITLE
Bug mise à la ligne 

### ISSUE THREAD

**Issue by nicosteo** [libreosteo/LibreOsteo#54]
![libreosteo](https://cloud.githubusercontent.com/assets/17109989/13078348/ad4041f6-d4be-11e5-9aa4-85abef61f9d7.jpg)

Je pense que l'image parle d'elle même 
Petit bug de découpage une mise à la ligne peut elle être mise en place ou une modification du cadre ...

Cordialement :smile:

**Comment by jbgury** [comment]
Serait il possible d'avoir le texte en mode "édition" svp ?

**Comment by nicosteo** [comment]
Je vous ai créé un patient bug affichage sur la démo avec ce test

![sans titre](https://cloud.githubusercontent.com/assets/17109989/13082495/3620a03a-d4d1-11e5-91b7-e4d8591c7c08.jpg)

**Comment by jbgury** [comment]
Mise en place de l'éditeur halloJs dans la consultation et fiche patient, éditeur WYSIWIG qui corrige le problème : commit : 52bdb9509f944268c0a3e77d58ce2d8a15aecb50
