### ISSUE TITLE
Pouvoir modifier date de consultation et contenu consultation

### ISSUE THREAD

**Issue by nicosteo** [libreosteo/LibreOsteo#56]
Je voulais rapatrier tranquillement mes dossiers patients dans libreosteo mais on ne peut pas modifier la date de la consultation donc impossible de faire ce rapatriement ... 

une fois la consultation terminé plus aucune action n'est possible
Or imaginons un peu de retard ou autre je veux effectuer la facturation et remplir le dossier ensuite je ne peux pas 
Ou si le patient me rappelle pour les résultats d'un examen après avoir été redirigé je ne peux pas le rajouter dans les commentaires de la consultations ... 

Serait-il possible de laissé la modification active ?

Cordialement :smile:

**Comment by jbgury** [comment]
Oui, en effet je comprends le besoin et je proposerai l'ouverture des modifs après facturation.
Concernant la date, ce sera probablement limité en raison de la facturation, ça signifie que si une facture a été établie, la date ne pourra pas être changée.

Quand à l'importation de vos consultations, je propose une fonctionnalité différente. Un import des anciennes consultations et réordonnancement de toute les consultations (même si saisies entre temps) par date.
Pour cela je propose d'établir des templates de fichiers "Tableur" qui seraient alors remplis par vos soins (ou export d'un autre logiciel), puis de lancer un script d'importation et intégrer toutes les données.

Qu'en pensez vous ? Car le besoin c'est d'importer les consultations, donc la fonction serait de pouvoir importer. Modifier la date n'est pas vraiment le besoin, c'est un moyen de pouvoir y arriver :) 
En revanche modifier la consultation après facturation. Je vais le faire pour les prochaines versions.

Ceci dit, vous pouvez toujours ajouter un commentaire à une consultation depuis la vue des consultations. Par exemple : https://garthylou.pythonanywhere.com/#/patient/1/examinations 
Observez au pied de la consultation du 21 avril 2015, il y a un commentaire.

**Comment by nicosteo** [comment]
Effectivement idéalement une feuille excel a compléter avec les différents champs qui seraient importés auto pourrait être une meilleur solution
Est ce déjà d'actualité ? car créer l'importateur n'est pas dans mes compétences à priori :S 

Même si la modification de date avant facturation pourrait toujours dépanner (panne info / consultation sur lieu ou pas ordinateur etc) 

Pour le commentaire je l'ai aperçu une fois mon post effectué :smiley:

**Comment by jbgury** [comment]
Le contenu de la consultation est modifiable après clôture, mais la date n'est pas modifiable. 
Commit 52bdb9509f944268c0a3e77d58ce2d8a15aecb50
