### ISSUE TITLE
Migration 0.4 vers 0.5

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#67]
Les derniers scripts de migrations sont appliqués après réindexation des patients. La migration et réindexation ne fonctionnent pas.
Il faut changer l'ordre des migrations (notamment la latéralité qui a été ajouté en dernier.

**Comment by jbgury** [comment]
revoir la migration de la feature #55

**Comment by littlejo** [comment]
Arf qu'est ce que j'ai fait de mal ?

**Comment by jbgury** [comment]
Non t'inquiète c'est l'empilement des migrations. Il faut que je les
réorganise. Si tu passes de la 0.4 à la 0.4.9.1 puis à la 0.4.9.2 c'est
bon. Le problème c'est qu'il y a un script de la beta 1 qui met à jour
l'index de la base patient sauf qu'il s'appuie sur le modèle Patient qui a
un champ laterality absent à ce stade du script. Je vais donc modifier
l'ordre d'exécution sur la branche develop.

**Comment by jbgury** [comment]
Corrigé par le commit 2e36da23280d0821c1568d265e4463c2a338e753
