### ISSUE TITLE
release definition 

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#72]
Dans la release, prévoir de changer la version du Dockerfile.
Definir la configuration pour simplifier le processus.

**Comment by littlejo** [comment]
Peut-être qu'au lieu de télécharger le tar.gz dans le Dockerfile, il est plus judicieux d'utiliser git sur la branche master ? Comme ça c'est toujours valide.

**Comment by jbgury** [comment]
Ça marche aussi oui 😊.
Mais la version du dockerfile n'a plus de sens est ce gênant pour docker ?

**Comment by littlejo** [comment]
> Mais la version du dockerfile n'a plus de sens est ce gênant pour docker ?

Non non, ce n'est pas obligatoire. Pour tester ma modification (latéralité), j'ai utilisé docker avec comme constante branch dévelop et mon dépot git.

Tu as vu ma doc sur docker ?

**Comment by jbgury** [comment]
ah non pas du tout. Je ne la trouve pas dans le wiki où l'as tu écrite ?

**Comment by littlejo** [comment]
Dans la section Linux:
https://github.com/libreosteo/Libreosteo/wiki/Installation-sous-GNU-Linux

**Comment by jbgury** [comment]
Excellent et merci pour ce beau travail
