### ISSUE TITLE
Règlement par CB

### ISSUE THREAD

**Issue by GitNitneroc** [libreosteo/LibreOsteo#77]
Les seuls moyens de paiement listés sont espèces et chèque, il serait intéressant d'ajouter la carte bleue

**Comment by jbgury** [comment]
oui c'est prévu de pouvoir ajouter différents mode de paiement à travers le module trésorerie

**Comment by JocelynDelalande** [comment]
je veux bien me charger d'ajouter le paiement par CB aux options.

**Comment by jbgury** [comment]
Si ça ne t'ennuie pas j'ai commencé le modèle PaimentMean, je voudrais bien continuer.

**Comment by JocelynDelalande** [comment]
Ah ben oui, au contraire :-)

**Comment by jkiwi** [comment]
j'ai remarqué une petite faute d'orthographe sur la version 0.5.7 (donc peut-être corrigée déjà ?).
sur la facture générée par un règlement en espèces, il n'y a pas de "s" à "espèces".

**Comment by jbgury** [comment]
Mis en place sur la branche develop
