### ISSUE TITLE
Liste des consultations

### ISSUE THREAD

**Issue by GitNitneroc** [libreosteo/LibreOsteo#78]
Quand on consulte la fiche d'un patient, on peut accéder à la liste de ses consultations. Mais si on clique sur une des consultations, il n'est alors plus possible de retourner à la liste des consultations, on revient toujours sur la consultation ouverte.
version 0.5.2

**Comment by jbgury** [comment]
ah je n'arrive pas à reproduire ce problème sur la version de démonstration. Lorsque je consulte la liste des consultations et que je clique sur une consultation, ensuite je clique sur la croix en haut à droite, et je reviens à la liste, en cliquant sur une autre consultation on accède à la liste.
Pourrais tu me confirmer que la croix en haut à droite de la fiche de consultation permet bien de revenir à la liste ?

**Comment by GitNitneroc** [comment]
Je n'avais pas vu cette croix en haut à droite. Ca marche parfaitement.

Peut-être par contre que ce n'est pas tout à fait intuitif ou assez visible, mais c'est clairement secondaire
