### ISSUE TITLE
Nom/login et capitales

### ISSUE THREAD

**Issue by GitNitneroc** [libreosteo/LibreOsteo#79]
Je ne sais pas si c'est un problème vraiment gênant, mais j'ai été surpris de voir que le nom d'utilisateur devait être correctement capitalizé : je n'arrive pas à me connecter avec "Andrew" puisque mon nom est "andrew" en minuscules.

**Comment by jbgury** [comment]
Pour le moment, aucun autre utilisateur n'a remonté ce problème. Il s'agit bien du 'login' au sens de connexion du logiciel.
Si on s'enregistre sur le logiciel avec une majuscule, il faut respecter cette majuscule pour la connexion, sinon le logiciel ne reconnaîtra pas.
Pour faire simple, il est possible sur libreosteo d'avoir l'utilisateur : 'andrew' et 'Andrew' qui sont au sens du logiciel, 2 utilisateurs différents. Est ce un problème ? Je préfère laisser la liberté aux utilisateurs de le juger.

**Comment by GitNitneroc** [comment]
Ok, aucun problème, j'ai juste été surpris de ce comportement.

Le 24 sept. 2016 3:04 PM, "Jean-Baptiste G." notifications@github.com a
écrit :
