### ISSUE TITLE
Facturer une séance après coup

### ISSUE THREAD

**Issue by GitNitneroc** [libreosteo/LibreOsteo#80]
J'ai récemment eu le cas d'une patiente qui ne m'a pas réglé après la séance (je l'ai clôturée comme "non facturée"), et qui m'a payé après coup. Je n'ai pas trouvé d'option pour indiqué la séance comme facturée et obtenir la facture.
Peut-être est-ce prévu pour le module compta ?
Est-ce que j'aurais mieux fait de ne pas clôturer la séance ?

Merci d'avance !

**Comment by jbgury** [comment]
Bonjour,

Il y a une option facturée/non réglée qui permettra par le module de compta
de reprendre et suivre les consultations non réglées. En mettant non
facturée, aucune facture ne peut être générée. Il n'est pas possible de
revenir sur ce mode.
Si l'objectif est de mettre à jour le règlement, il vaut mieux mettre
facturée non réglée.

En revanche, comme ce mode n'est pas encore implémenté pour le module
compta, il vaut mieux pour vous ne pas clôturer la séance et attendre le
mode de règlement.



Le 26 septembre 2016 à 15:22, GitNitneroc notifications@github.com a
écrit :

**Comment by GitNitneroc** [comment]
Merci !

Le 27 sept. 2016 9:08 PM, "Jean-Baptiste G." notifications@github.com a
écrit :

**Comment by JocelynDelalande** [comment]
Suggestion immédiate : masquer cette option qui n'a pas d'existence technique.

**Comment by JocelynDelalande** [comment]
Je veux bien me charger de masquer cette option (pour le moment)

L'idée à terme étant bien évidement d'offrir la possibilité.

L'idée à court terme étant de ne pas tromper l'utilisateur et de le laisser dans une impasse.

**Comment by JocelynDelalande** [comment]
> Suggestion immédiate : masquer cette option qui n'a pas d'existence technique.

Cette idée est déjà mise en place (depuis #77  je pense). Il n'y a plus d'option « non réglé » dans l'interface.

**Comment by jbgury** [comment]
L'option est rétablie dans la version 0.6.0 : 
  - il est possible de marquer une séance non réglée
 - la régularisation peut être faite a posteriori

**Comment by JocelynDelalande** [comment]
Je confirme : ça marche tout bien comme il faut :)
