### ISSUE TITLE
Vue consultation sur 2 colonnes

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#83]
Il s'agit de revoir la vue consultation

Fiche actuelle : 
![screenshot-localhost 8000 2017-03-23 14-27-34](https://cloud.githubusercontent.com/assets/429633/24249752/c436fd44-0fd4-11e7-8ddf-19645d544589.png)

Constatant qu'en consultation, on a besoin d'avoir sous les yeux à la fois la fiche patient et la fiche de la consultation en cours (et de pouvoir éditer chacune) nous aurions donc 2 volets :

- la fiche consultation à proprement parler
- un volet d'informations éditables propres au patient

Techniquement, il faudrait probablement :

- [x] faire une maquette statique (wireframe ou autre)
- [x] discuter
- [x] revoir la template pour implémenter cette feature

lié (mais non équivalent à) https://github.com/libreosteo/Libreosteo/issues/47

*votes : +++++*

**Comment by JocelynDelalande** [comment]
Voici une première maquette d'une fiche consult sur deux colones. Pour rappel, l'objectif est d'**avoir tout ce qu'il faut sous les yeux en consultation** ; les infos de la consultation en cours comme celles concernant le patient quelle que soit la consultation.

![image](https://user-images.githubusercontent.com/429633/36861697-f0c2477e-1d84-11e8-98ac-50d7e1c29910.png)


NB:

- dans une version « réelle », l'édition basculera aussi les champs de la colonne de droite en mode formulaire.
- j'ai choisi de laisser les comptes-rendus médicaux dans leur propre onglet, pour éviter d'alourdir une vue déjà bien chargée
- la suppression de la sidebar (cf #85) devrait donner un peu davantage d'espace en largeur pour ce contenu sur deux colones

Je met en pause le développement de cette modification tant que la discussion n'a pas atteint un consensus ou un compromis.

**Au boulot : à vos retours/remarques :-).**

(je propose que l'on ne discute pas ici de la pertinence de tel ou tel champ, d'une part, c'est un autre sujet, d'autre part @jbgury a [récemment exprimé son souhait de garder tous les champs](https://github.com/libreosteo/Libreosteo/issues/86#issuecomment-366430124))

**Comment by littlejo** [comment]
Est-ce que vous avez prévu une vue responsive (pour tablette, voir téléphone)?

**Comment by JocelynDelalande** [comment]
@littlejo oui, l'idée est de conserver l'aspect responsive.

**Comment by jbgury** [comment]
C'est proposition est très intéressante, cela me parait très bien comme ça. Faudra être vigilant sur l'édition de ce deuxième formulaire et l'édition depuis l'onglet info patient. Les contextes sont séparés et pourtant ce sont les mêmes infos.

**Comment by JocelynDelalande** [comment]
@jbgury youpi :) Je prend bonne note des histoires d'édition, il y a effectivement un peu de travail technique là dessus au niveau des formulaires.

Notes suite à discussion avec @jkiwi:

- [x] on pourrait rendre plus compact le sélecteur de type de consult (urgent/normal/suivi), par exemple en utilisant un badge¹
- [x] la profession et l'age seraient en sous-titre plutôt que dans la colone de droite.
- [x] dans l'onglet « Fiche patient », séparer les infos le la colone de gauche en deux encadrés :
  - [x] un premier identité / contact
  - [x] un deuxième « infos générales » (reprenant fumeur / latéralité / loisir…) avec éventuellement une petite note pour expliquer que ces infos sont éditables également dans la vue consultation.
- [x] Rendre l'affichage des sphères totalement désactivables (même type d'options que #84 )
- [x] Les blocs « antécédents » : éviter les colones trop étroites

On a donc un affichage de certaines infos **répété dans 2 onglets**.

¹ cette option, semble peu utilisée, au moins dans les discussions que @jkiwi et moi avons pu avoir avec d'autres praticiens.

**Comment by jbgury** [comment]
Explications sur la sélection du mode de consultation (qui est en lien avec le tableau de bord). Cela permet de faire ressortir rapidement s'il a fallu revoir rapidement le patient après une consultation, si le patient a déjà été traité au travers d'une urgence.
car ces indicateurs servent au thérapeute. Trop de retour sur semaine/mois peut traduire une fatigue du thérapeute, que cela a des impacts sur les traitements qu'il fait. Permet aussi de s'améliorer ou d'identifier sur quels traitements il est préférable qu'il s'améliore. Avec ceux avec qui il avait été établi, ceci permettait l'amélioration continue du therapeute/cabinet d'identifier des faiblesses et donc tenté dans le coeur de métier de l'ostéopathe. Je ne suis pas pour le rendre optionel à ce titre. Le dashboard pourrait sans doute être amélioré pour être plus intelligent. Mais c'est un autre sujet.

**Comment by jbgury** [comment]
L'outil badge peut répondre à ce besoin oui. Mais le laisser par défaut me paraît essentiel

**Comment by JocelynDelalande** [comment]
Merci pour les détails :)

> L'outil badge peut répondre à ce besoin oui. Mais le laisser par défaut me paraît essentiel

Je ne proposais pas de le masquer par défaut, simplement de le présenter sous forme de badge, afin qu'il occupe moins d'espace sur la page.

**Comment by jkiwi** [comment]
> L'outil badge peut répondre à ce besoin oui. Mais le laisser par défaut me paraît essentiel

@jbgury aucun problème pour garder l'option (surtout si des collègues l'utilisent en production). Un badge permettrait de favoriser l'affichage des infos patients dans la fiche de consultation tout en gardant cette possibilité pour le praticien (car comme tu le précise, c'est plus une option pour le praticien). Merci de l'avoir expliqué en tout cas, je comprends que ça puisse être utile et chacun·e choisira ou non de l'employer.

**Comment by JocelynDelalande** [comment]
On est très très proches du but :-)

**Comment by JocelynDelalande** [comment]
C'est plus que fait :-).  (via eada3e0 et plein d'autres).

Ménage de printemps ! :rose:
