### ISSUE TITLE
Suppression de la sidebar au profit d'un header fixe

### ISSUE THREAD

**Issue by opi** [libreosteo/LibreOsteo#85]
Constat que la sidebar est assez vide, et occupe donc de la place qui pourrait être mise a profit autrement (https://github.com/libreosteo/Libreosteo/issues/83).

Les infos généralement trouvée dans cette sidebar sont : 
- Bouton "Ajout patient"
- Boutons "Edit" / "Delete"
- Recherche

Ces actions peuvent largement passer dans un header, fixe au scroll. Exemple : https://getbootstrap.com/examples/navbar-fixed-top/  ou http://patience.dev.olivierpierre.net

- Ajouter un bouton/lien "Nouveau patient" ?

----

*Notes originales*
*Colonne de gauche Très peu utilisée au final*
*- en haut (= menu), fixes (même lorsqu'on scrolle)*
*- y intégrer le champ de recherche (celui actuellement présent sur la barre de gauche)*
*Vote: +++*

**Comment by JocelynDelalande** [comment]
Fait via #105, peut être fermé.

**Comment by JocelynDelalande** [comment]
bump, à fermer.
