### ISSUE TITLE
Revoir la structure de la fiche patient

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#86]
Dans la section infos générales, on aurait :

- Nom +  Prénom (qui sont donc redondants avec le titre de la page¹)
- Sexe
- Date de naissance
- Profession
- adresse
- téléphone
- e-mail

Ça revient un peu à la maquette http://patience.dev.olivierpierre.net/fiche-patient.html à ceci près :

- on vire n° sécu et mutuelle de la section « infos générales
- on met le nom avant le prénom

Plusieurs boutons de validation (éventuellement bouton avec actions déroulantes)

- Enregistrer
- Enregister et démarer une consultation
- (Enregister et prendre un RDV)

¹ Pourquoi ce choix de redondance ? Parce qu'actuellement, la manière d'éditer le nom/prénom est très peu intuitive.

cf aussi #82 

*vote: +++*

**Comment by jbgury** [comment]
Pour répondre à l'édition Nom Prénom peu intuitive :), en même temps on ne change pas de nom et prénom souvent. L'intérêt de remplir un champ pour ça me parait assez peu valuable.

Pour le reste, il est important de conserver toutes les infos existantes, elles ont été demandées par les différents ostéopathes précédent le mécénat, merci de ne pas les supprimer

**Comment by jkiwi** [comment]
> Pour le reste, il est important de conserver toutes les infos existantes, elles ont été demandées par les différents ostéopathes précédent le mécénat, merci de ne pas les supprimer

@jbgury : y compris les infos sur : fumeur/non fumeur ? et la latéralité (droitier/gaucher) ? Selon moi ce sont 2 infos qui sont utiles sur la fiche de consultation pour établir un diagnostique et non dans la partie purement administrative (nom/prénom...) lors de la création d'une fiche.
(sinon pourquoi ne pas ajouter la prise d'alcool, cannabis, pathologies, ... bref l'intérêt de cibler la consult en fonction des besoins).

Tout le reste fait bien évidemment consensus.

(Petit bémol tout de même sur les "loisirs" qui est une donnée qui peut souvent changer et qui peut être utile sur la fiche de consultation... mais ce point peut se discuter...)

**Comment by jbgury** [comment]
@jkiwi les infos fumeur/non fumeur, latéralité sont relatives à un patient et non à une consultation. Ok toutes les infos patients aident à la consultation ça je suis d'accord, mais ce sont des informations propre au patient. D'une consultation à une autre, les infos de ce type ne changent pas.
Ces informations s'éditent et peuvent également se changer au besoin, elles participent au diagnostic c'est certain sinon il n'y aurait pas ces infos, mais ressaisir les infos pour une consultation n'a pas de sens. 

Si vous voulez accéder aux infos durant la consultation et que la navigation ne vous convient pas, alors c'est plutot la présentation des données qui est importante.

**Comment by jkiwi** [comment]
@jbgury au final je crois que nous sommes d'accord, c'est juste une différence de terminologie (j'ai eu le même soucis avec Jocelyn ^_^). Et je crois avoir mal utilisé le terme consultation dans mon post précédent ce qui a pu porter à confusion.
Je trouve la solution de Jocelyn très élégante : faire un rappel de ces infos dans un encadré dans l'onglet consultation, ce qui permet de ne pas casser les habitudes existantes tout en offrant de nouvelle possibilité. Donc oui, au final c'est juste une question de présentation... (cf #83 ).

Pour essayer d'être peut-être un peu plus clair dans mon propos, pour moi une fiche patient se divise globalement en 3 parties : 
- la partie purement "administrative" (nom, prénom, adresse...)
- la partie "histoire du patient" (médicament, chirurgie, trauma, latéralité, tabac, alcool, loisirs...) qui effectivement ne change pas et n'a pas de sens à être réécrite à chaque fois.
- la partie "consultation du jour" (le motif, le traitement du jour, ...) 

C'est pour cela que je ne comprenais pas que certaines infos comme fumeur/non fumeur, médicament soit placées avec les infos générales administratives (et non pas dans l'onglet "antécédent" par exemple).
Mais à nouveau, la solution de Jocelyn me semble simple et facile pour s'adapter aux différents mode de fonctionnement des ostéopathes.

**Comment by jkiwi** [comment]
Petit retour de dernière minute, est-ce qu'il ne serait pas intéressant de rajouter "ambidextre" dans le choix des latéralités ?

**Comment by JocelynDelalande** [comment]
@jkiwi autre question, autre ticket :)

**Comment by JocelynDelalande** [comment]
Fait
