### ISSUE TITLE
Demander une confirmation pour quitter une page en mode édition

### ISSUE THREAD

**Issue by opi** [libreosteo/LibreOsteo#87]
Lors de l'édition d'une fiche patient, si l'utilisateur clique sur le lien de retour à l'accueil, les données modifiées ne sont pas sauvegardées.

Cette demande rejoint l'idée de proposer les fiches (patient / consult) en mode édition par défaut (donc sans devoir cliquer sur "éditer"), avec une sauvegarde automatique. A voir quelle solution est préférable pour l'experience utilisateur.

**Comment by jbgury** [comment]
Comme déjà dit, les actions "éditions", "suppression" ont été demandées par les utilisateurs. Les premières versions permettaient du "in line", et ça ne correspondait pas à leurs attentes. Trouvant la fonction peu intuitive. Je suis d'accord avec vous c'est une étape en plus... J'ai été déçu de l'introduire. Mais elle avait été demandée.

**Comment by jbgury** [comment]
Par contre je vous rejoins, la confirmation de fermeture pendant l'édition c'est clairement un truc à faire :)
