### ISSUE TITLE
Export CSV/tableur pour compta

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#89]
Cette fonctionnalité serait accessible depuis la liste des factures #88 

Pour facturation notamment avec / sans nom des patients (anonymisation pour éviter de donner des infos perso au comptable).

*note: ++*

**Comment by jbgury** [comment]
Clairement y a pas grand chose à faire pour y arriver, je pense que je peux m'en occuper, au besoin

**Comment by JocelynDelalande** [comment]
Corrigé par #110
