### ISSUE TITLE
Enlever l'édition modale (boutons « Édition » / « Fin d'édition »)

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#90]
On voudrait pouvoir éditer directement sans ce mécanisme de « mode édition » / « mode consultation », plusieurs autres approches existent :

- avoir des éléments éditables par défaut
- sauvegarde automatique OU bouton sauvegarde.

sujet discuté également dans #87, et concerne également la refonte de la fiche patient #20 

*vote: ++*

**Comment by jbgury** [comment]
C'était le cas dans les premières versions 0.0.1, et 0.0.2, cela a été demandé de le supprimer ensuite :)
A voir si une autre méthode peut convenir

**Comment by JocelynDelalande** [comment]
Du coup, on va laisser ça de côté, au moins pour l'instant. (tu peux taguer « wontfix » ?).
