### ISSUE TITLE
Label « ostéo-mécène »

### ISSUE THREAD

**Issue by JocelynDelalande** [libreosteo/LibreOsteo#92]
Pourrait-on avoir un label « ostéo-mécène » (ou tout autre nom) pour les tickets créés @opi et moi-même : #82 #83 #84 #85 #86 #87 #88 #89 #90 #91 .

Ce afin que les ostéos partenaires du financement participatif puissent les identifier.

Merci :-)

**Comment by jbgury** [comment]
C'est fait ! 
Merci à vous
